// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.16/esri/copyright.txt for details.
//>>built
define("esri/PopupInfo","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/json dojo/i18n dojo/has dojo/Deferred dojo/sniff dojo/promise/all ./lang ./kernel ./request ./tasks/query ./tasks/QueryTask ./tasks/StatisticDefinition dojo/i18n!dojo/cldr/nls/number".split(" "),function(r,g,n,C,M,H,D,I,y,p,E,J,F,K,L,G){r=r(null,{declaredClass:"esri.PopupInfo",initialize:function(a,b){if(a){g.mixin(this,b);this.info=a;this.title=this.getTitle;this.content=this.getContent;var c=this._fieldLabels=
{},d=this._fieldsMap={};a.fieldInfos&&n.forEach(a.fieldInfos,function(a){var b=a.fieldName.toLowerCase();c[b]=a.label;d[b]=a});this._relatedFieldPrefix="relationships/";this.titleHasRelatedFields=!!(a.title&&-1!==a.title.indexOf("{"+this._relatedFieldPrefix))}},toJson:function(){return C.fromJson(C.toJson(this.info))},getTitle:function(){},getContent:function(){},getFieldInfo:function(a){var b;n.some(this.info&&this.info.fieldInfos,function(c){c.fieldName===a&&(b=c);return!!b});return b},getComponents:function(a){var b=
this.info,c=new D,d,e;b.fieldInfos&&(e=n.filter(b.fieldInfos,function(a){return-1!==a.fieldName.indexOf(this._relatedFieldPrefix)},this));e&&0<e.length&&(d=this._getRelatedRecords({graphic:a,fieldsInfo:e}));d?d.always(g.hitch(this,function(){c.resolve(this._getPopupValues(a))})):c.resolve(this._getPopupValues(a));return c.promise},getAttachments:function(a){var b=a.getLayer();a=a.attributes;if(this.info.showAttachments&&(b&&b.hasAttachments&&b.objectIdField)&&(a=a&&a[b.objectIdField]))return b.queryAttachmentInfos(a)},
_getPopupValues:function(a,b){var c=this.info,d=a.getLayer(),e=g.clone(a.attributes)||{},f=g.clone(e),q=c.fieldInfos,k="",m="",u,h,l,w,s,v=d&&d._getDateOpts&&d._getDateOpts().properties,v=v&&v.slice(0),t={dateFormat:{properties:v,formatter:"DateFormat"+this._insertOffset(this._dateFormats.shortDateShortTime)}};if(this._relatedInfo)for(w in this._relatedInfo)if(this._relatedInfo.hasOwnProperty(w)){var x=this._relatedInfo[w],r=this._relatedLayersInfo[w];x&&(n.forEach(x.relatedFeatures,function(a){for(s in a.attributes)if(a.attributes.hasOwnProperty(s)&&
"esriRelCardinalityOneToOne"===r.relation.cardinality){var b=this._toRelatedFieldName([r.relation.id,s]);e[b]=f[b]=a.attributes[s]}},this),n.forEach(x.relatedStatsFeatures,function(a){for(s in a.attributes)if(a.attributes.hasOwnProperty(s)){var b=this._toRelatedFieldName([r.relation.id,s]);e[b]=f[b]=a.attributes[s]}},this))}q&&n.forEach(q,function(a){h=a.fieldName;var b=this._getLayerFieldInfo(d,h);b&&(h=a.fieldName=b.name);f[h]=this._formatValue(f[h],h,t);v&&(a.format&&a.format.dateFormat)&&(a=n.indexOf(v,
h),-1<a&&v.splice(a,1))},this);if(d){w=d.types;var y=(x=d.typeIdField)&&e[x];for(h in e)if(e.hasOwnProperty(h)&&-1===h.indexOf(this._relatedFieldPrefix)&&(l=e[h],p.isDefined(l))){var z=this._getDomainName(d,a,w,y,h,l);p.isDefined(z)?f[h]=z:h===x&&(z=this._getTypeName(d,a,l),p.isDefined(z)&&(f[h]=z))}}c.title&&(k=this._processFieldsInLinks(this._fixTokens(c.title,d),e),k=g.trim(p.substitute(f,k,t)||""));if(b)return{title:k};c.description&&(m=this._processFieldsInLinks(this._fixTokens(c.description,
d),e),m=g.trim(p.substitute(f,m,t)||""));q&&(u=[],n.forEach(q,function(a){(h=a.fieldName)&&a.visible&&u.push([a.label||h,p.substitute(f,"${"+h+"}",t)||""])}));var A,B;c.mediaInfos&&(A=[],n.forEach(c.mediaInfos,function(a){B=0;l=a.value;switch(a.type){case "image":var b=l.sourceURL,b=b&&g.trim(p.substitute(e,this._fixTokens(b,d)));B=!!b;break;case "piechart":case "linechart":case "columnchart":case "barchart":var c,b=l.normalizeField;l.fields=n.map(l.fields,function(a){return(c=this._getLayerFieldInfo(d,
a))?c.name:a},this);b&&(c=this._getLayerFieldInfo(d,b),l.normalizeField=c?c.name:b);B=n.some(l.fields,function(a){return p.isDefined(e[a])||-1!==a.indexOf(this._relatedFieldPrefix)&&this._relatedInfo},this);break;default:return}if(B){a=g.clone(a);l=a.value;var b=a.title?this._processFieldsInLinks(this._fixTokens(a.title,d),e):"",h=a.caption?this._processFieldsInLinks(this._fixTokens(a.caption,d),e):"";a.title=b?g.trim(p.substitute(f,b,t)||""):"";a.caption=h?g.trim(p.substitute(f,h,t)||""):"";if("image"===
a.type)l.sourceURL=p.substitute(e,this._fixTokens(l.sourceURL,d)),l.linkURL&&(l.linkURL=g.trim(p.substitute(e,this._fixTokens(l.linkURL,d))||""));else{var k,q;n.forEach(l.fields,function(a,b){if(-1!==a.indexOf(this._relatedFieldPrefix))q=this._getRelatedChartInfos(a,l,e,t),q instanceof Array?l.fields=q:l.fields[b]=q;else{var c=e[a],c=void 0===c?null:c;k=e[l.normalizeField]||0;c&&k&&(c/=k);l.fields[b]={y:c,tooltip:(this._fieldLabels[a.toLowerCase()]||a)+":\x3cbr/\x3e"+this._formatValue(c,a,t,!!k)}}},
this)}A.push(a)}},this));return{title:k,description:m,hasDescription:!!c.description,fields:u&&u.length?u:null,mediaInfos:A&&A.length?A:null,formatted:f,editSummary:d&&d.getEditSummary?d.getEditSummary(a):""}},_getRelatedChartInfos:function(a,b,c,d){var e,f,q,k,m,g;e=[];g=this._fromRelatedFieldName(a);m=g[0];f=this._relatedInfo[m];m=this._relatedLayersInfo[m];f&&n.forEach(f.relatedFeatures,function(f){f=f.attributes;var l,m;for(m in f)if(f.hasOwnProperty(m)&&m===g[1]){l={};k=f[m];b.normalizeField&&
(q=-1!==b.normalizeField.indexOf(this._relatedFieldPrefix)?f[this._fromRelatedFieldName(b.normalizeField)[1]]:c[b.normalizeField]);k&&q&&(k/=q);if(b.tooltipField)if(-1!==b.tooltipField.indexOf(this._relatedFieldPrefix)){var n=this._fromRelatedFieldName(b.tooltipField)[1];l.tooltip=f[n]&&"string"===typeof f[n]?f[n]+":\x3cbr/\x3e"+this._formatValue(k,f[n],d,!!q):n+":\x3cbr/\x3e"+this._formatValue(k,n,d,!!q)}else l.tooltip=(this._fieldLabels[a.toLowerCase()]||a)+":\x3cbr/\x3e"+this._formatValue(k,b.tooltipField,
d,!!q);else l.tooltip=k;l.y=k;e.push(l)}},this);return"esriRelCardinalityOneToMany"===m.relation.cardinality||"esriRelCardinalityManyToMany"===m.relation.cardinality?e:e[0]},_dateFormats:{shortDate:"(datePattern: 'M/d/y', selector: 'date')",shortDateLE:"(datePattern: 'd/M/y', selector: 'date')",longMonthDayYear:"(datePattern: 'MMMM d, y', selector: 'date')",dayShortMonthYear:"(datePattern: 'd MMM y', selector: 'date')",longDate:"(datePattern: 'EEEE, MMMM d, y', selector: 'date')",shortDateShortTime:"(datePattern: 'M/d/y', timePattern: 'h:mm a', selector: 'date and time')",
shortDateLEShortTime:"(datePattern: 'd/M/y', timePattern: 'h:mm a', selector: 'date and time')",shortDateShortTime24:"(datePattern: 'M/d/y', timePattern: 'H:mm', selector: 'date and time')",shortDateLEShortTime24:"(datePattern: 'd/M/y', timePattern: 'H:mm', selector: 'date and time')",shortDateLongTime:"(datePattern: 'M/d/y', timePattern: 'h:mm:ss a', selector: 'date and time')",shortDateLELongTime:"(datePattern: 'd/M/y', timePattern: 'h:mm:ss a', selector: 'date and time')",shortDateLongTime24:"(datePattern: 'M/d/y', timePattern: 'H:mm:ss', selector: 'date and time')",
shortDateLELongTime24:"(datePattern: 'd/M/y', timePattern: 'H:mm:ss', selector: 'date and time')",longMonthYear:"(datePattern: 'MMMM y', selector: 'date')",shortMonthYear:"(datePattern: 'MMM y', selector: 'date')",year:"(datePattern: 'y', selector: 'date')"},_reHref:/href\s*=\s*\"([^\"]+)\"/ig,_reHrefApos:/href\s*=\s*\'([^\']+)\'/ig,_fixTokens:function(a,b){var c=this;return a.replace(/(\{([^\{\r\n]+)\})/g,function(a,e,f){a=c._getLayerFieldInfo(b,f);return"$"+(a?"{"+a.name+"}":e)})},_encodeAttributes:function(a){a=
g.clone(a)||{};var b,c;for(b in a)if((c=a[b])&&"string"===typeof c)c=encodeURIComponent(c).replace(/\'/g,"\x26apos;"),a[b]=c;return a},_processFieldsInLinks:function(a,b){var c=this._encodeAttributes(b),d=this;a&&(a=a.replace(this._reHref,function(a,f){return d._addValuesToHref(a,f,b,c)}).replace(this._reHrefApos,function(a,f){return d._addValuesToHref(a,f,b,c)}));return a},_addValuesToHref:function(a,b,c,d){b=b&&g.trim(b);return p.substitute(b&&0===b.indexOf("${")?c:d,a)},_getLayerFieldInfo:function(a,
b){return a&&a.getField?a.getField(b):null},_formatValue:function(a,b,c,d){var e=this._fieldsMap[b.toLowerCase()],f=e&&e.format;b=-1!==n.indexOf(c.dateFormat.properties,b);var q="number"===typeof a&&!b&&(!f||!f.dateFormat);if(!p.isDefined(a)||!e||!p.isDefined(f))return q?this._forceLTR(a):a;var k="",e=[],m=f.hasOwnProperty("places")||f.hasOwnProperty("digitSeparator"),u=f.hasOwnProperty("digitSeparator")?f.digitSeparator:!0;if(m&&!b)k="NumberFormat",e.push("places: "+(p.isDefined(f.places)&&(!d||
0<f.places)?Number(f.places):"Infinity")),e.length&&(k+="("+e.join(",")+")");else if(f.dateFormat)k="DateFormat"+this._insertOffset(this._dateFormats[f.dateFormat]||this._dateFormats.shortDateShortTime);else return q?this._forceLTR(a):a;var h=this._applyFormatting(a,k,c);m&&-1<a.constructor.toString().indexOf("Array")&&(h="",n.forEach(a,g.hitch(this,function(a){h=h+this._applyFormatting(a,k,c)+" "})));m&&!u&&G.group&&(h=h.replace(RegExp("\\"+G.group,"g"),""));return q?this._forceLTR(h):h},_applyFormatting:function(a,
b,c){return p.substitute({myKey:a},"${myKey:"+b+"}",c)||""},_forceLTR:function(a){var b=I("ie");return b&&10>=b?a:"\x3cspan class\x3d'esriNumericValue'\x3e"+a+"\x3c/span\x3e"},_insertOffset:function(a){a&&(a=p.isDefined(this.utcOffset)?a.replace(/\)\s*$/,", utcOffset:"+this.utcOffset+")"):a);return a},_getDomainName:function(a,b,c,d,e,f){return(a=a.getDomain&&a.getDomain(e,{feature:b}))&&a.codedValues?a.getName(f):null},_getTypeName:function(a,b,c){return(a=a.getType&&a.getType(b))&&a.name},_getRelatedRecords:function(a){var b=
a.graphic,c=new D,d;this._relatedLayersInfo?this._queryRelatedLayers(b).then(g.hitch(this,function(a){this._setRelatedRecords(b,a);c.resolve(a)}),g.hitch(this,this._handlerErrorResponse,c)):this._getRelatedLayersInfo(a).then(g.hitch(this,function(a){for(d in a)a.hasOwnProperty(d)&&a[d]&&(this._relatedLayersInfo[d].relatedLayerInfo=a[d]);this._queryRelatedLayers(b).then(g.hitch(this,function(a){this._setRelatedRecords(b,a);c.resolve(a)}),g.hitch(this,this._handlerErrorResponse,c))}),g.hitch(this,this._handlerErrorResponse,
c));return c.promise},_getRelatedLayersInfo:function(a){var b=a.fieldsInfo,c,d,e={};c=a.graphic.getLayer();this._relatedLayersInfo||(this._relatedLayersInfo={});n.forEach(b,function(a){var b,d,e,g;b=this._fromRelatedFieldName(a.fieldName);d=b[0];b=b[1];d&&(this._relatedLayersInfo[d]||(n.some(c.relationships,function(a){if(a.id==d)return g=a,!0}),g&&(this._relatedLayersInfo[d]={relation:g,relatedFields:[],outStatistics:[]})),this._relatedLayersInfo[d]&&(this._relatedLayersInfo[d].relatedFields.push(b),
a.statisticType&&(e=new L,e.statisticType=a.statisticType,e.onStatisticField=b,e.outStatisticFieldName=b,this._relatedLayersInfo[d].outStatistics.push(e))))},this);for(d in this._relatedLayersInfo)this._relatedLayersInfo.hasOwnProperty(d)&&this._relatedLayersInfo[d]&&(a=this._relatedLayersInfo[d].relation,a=c.url.replace(/[0-9]+$/,a.relatedTableId),this._relatedLayersInfo[d].relatedLayerUrl=a,e[d]=J({url:a,content:{f:"json"},callbackParamName:"callback"}));return y(e)},_queryRelatedLayers:function(a){var b=
{},c;for(c in this._relatedLayersInfo)this._relatedLayersInfo.hasOwnProperty(c)&&(b[c]=this._queryRelatedLayer({graphic:a,relatedInfo:this._relatedLayersInfo[c]}));return y(b)},_queryRelatedLayer:function(a){var b,c,d,e,f,g,k,m,p,h;b=a.graphic;c=b.getLayer().url.match(/[0-9]+$/g)[0];m=a.relatedInfo;k=m.relatedLayerInfo;p=m.relatedLayerUrl;h=m.relation;n.some(k.relationships,function(a){if(a.relatedTableId===parseInt(c,10))return d=a,!0},this);d&&(a=new F,n.some(k.fields,function(a){if(a.name===d.keyField)return f=
-1!==n.indexOf(["esriFieldTypeSmallInteger","esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble"],a.type)?"number":"string",!0}),e="string"===f?d.keyField+"\x3d'"+b.attributes[h.keyField]+"'":d.keyField+"\x3d"+b.attributes[h.keyField],a.where=e,a.outFields=m.relatedFields,m.outStatistics&&(0<m.outStatistics.length&&k.supportsStatistics)&&(g=new F,g.where=a.where,g.outFields=a.outFields,g.outStatistics=m.outStatistics),b=new K(p),e=[],e.push(b.execute(a)),g&&e.push(b.execute(g)));return y(e)},
_setRelatedRecords:function(a,b){this._relatedInfo=[];for(var c in b)if(b.hasOwnProperty(c)&&b[c]){var d=b[c];this._relatedInfo[c]={};this._relatedInfo[c].relatedFeatures=d[0].features;p.isDefined(d[1])&&(this._relatedInfo[c].relatedStatsFeatures=d[1].features)}},_handlerErrorResponse:function(a,b){a.reject(b)},_fromRelatedFieldName:function(a){var b=[];-1!==a.indexOf(this._relatedFieldPrefix)&&(a=a.split("/"),b=a.slice(1));return b},_toRelatedFieldName:function(a){var b="";a&&0<a.length&&(b=this._relatedFieldPrefix+
a[0]+"/"+a[1]);return b}});H("extend-esri")&&(E.PopupInfo=E.PopupInfoTemplate=r);return r});