// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.16/esri/copyright.txt for details.
//>>built
define("esri/renderers/Renderer","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has dojox/gfx/_base ../kernel ../Color ../arcade/arcade".split(" "),function(s,m,e,z,r,E,q,v){var x=Math.PI;s=s(null,{declaredClass:"esri.renderer.Renderer",constructor:function(a){this._cache={};if(a&&!a.declaredClass){this.rotationInfo=a.rotationInfo;if(!this.rotationInfo){var b=a.rotationType,c=a.rotationExpression;if(b||c)this.rotationInfo={type:b,expression:c}}this.setRotationInfo(this.rotationInfo);this.setSizeInfo(this._readSizeInfo(a.sizeInfo));
this.setColorInfo(this._readColorInfo(a.colorInfo));this.setOpacityInfo(this._readOpacityInfo(a.transparencyInfo));this.setVisualVariables(this._readVariables(a.visualVariables));this.setAuthoringInfo(a.authoringInfo)}this.getSymbol=m.hitch(this,this.getSymbol)},getSymbol:function(a){},_readSizeInfo:function(a){if(a){var b=a.minSize,c=a.maxSize;b&&"number"===typeof b&&(a.minSize=r.pt2px(b));c&&"number"===typeof c&&(a.maxSize=r.pt2px(c))}return a},_readColorInfo:function(a){a&&(e.forEach(a.colors,
function(b,c){m.isArray(b)&&(a.colors[c]=q.toDojoColor(b))}),e.forEach(a.stops,function(b,c){b.color&&m.isArray(b.color)&&(a.stops[c].color=q.toDojoColor(b.color))}));return a},_readOpacityInfo:function(a){var b;a&&(b=m.mixin({},a),b.transparencyValues&&(b.opacityValues=e.map(b.transparencyValues,function(a){return 1-a/100}),delete b.transparencyValues),b.stops&&(b.stops=e.map(b.stops,function(a){a=m.mixin({},a);a.opacity=1-a.transparency/100;delete a.transparency;return a})));return b},_readVariables:function(a){a&&
(a=e.map(a,function(a){"sizeInfo"===a.type?a=this._readSizeInfo(a):"colorInfo"===a.type?a=this._readColorInfo(a):"transparencyInfo"===a.type&&(a=this._readOpacityInfo(a),a.type="opacityInfo");return a},this));return a},setAuthoringInfo:function(a){this.authoringInfo=a},setRotationInfo:function(a){if(a=this.rotationInfo="string"===typeof a?{field:a}:a){if(a.expression&&!m.isFunction(a.expression)&&!a.field){var b=a.expression.match(this.rotationRE);b&&b[1]&&(a.field=b[1])}a.rotationType=a.type}return this},
rotationRE:/^\[([^\]]+)\]$/i,getRotationAngle:function(a,b){var c=this._getVarInfo(b&&b.rotationInfo,"rotationInfo").variable,d="arithmetic"===this._getRotationType(c),c=c.field,f=a.attributes,k=0;c&&(m.isFunction(c)?k=c.apply(this,arguments):f&&(k=f[c]||0),k=(k+(d?-90:0))*(d?-1:1));return k},_getRotationType:function(a){return a&&("rotationInfo"===a.type?a.rotationType:a.type)},setVisualVariables:function(a){var b=this._cache;e.forEach(this.visualVariables,function(a,d){b.hasOwnProperty(d)&&(b[d]=
null)},this);this.visualVariables=a;e.some(a,function(a){return!!a.target})&&a.sort(function(a,b){return a.target===b.target?0:a.target?1:-1});e.forEach(a,function(a,d){"colorInfo"===a.type?b[d]=this._processColorInfo(a):"opacityInfo"===a.type?b[d]=this._processOpacityInfo(a):"sizeInfo"===a.type&&(b[d]=this._processSizeInfo(a))},this);return this},getVisualVariableValues:function(a){var b=this.visualVariables,c;b&&(c=e.map(b,function(b){var c;switch(b.type){case "sizeInfo":c=this.getSize(a,{sizeInfo:b});
break;case "colorInfo":c=this.getColor(a,{colorInfo:b});break;case "opacityInfo":c=this.getOpacity(a,{opacityInfo:b});break;case "rotationInfo":c=this.getRotationAngle(a,{rotationInfo:b})}return{variable:b,value:c}},this));return c},hasVisualVariables:function(a,b){return a?!!this.getVisualVariablesForType(a,b):!(!this.getVisualVariablesForType("sizeInfo",b)&&!this.getVisualVariablesForType("colorInfo",b)&&!this.getVisualVariablesForType("opacityInfo",b)&&!this.getVisualVariablesForType("rotationInfo",
b))},getVisualVariablesForType:function(a,b){var c=this.visualVariables,d;!b&&this[a]?("rotationInfo"===a&&(this[a].rotationType=this[a].type),d=[this[a]]):c&&(d=e.filter(c,function(c){return c.type===a&&("string"===typeof b?c.target===b:!1===b?!c.target:!0)}))&&0===d.length&&(d=void 0);return d},setSizeInfo:function(a){this.sizeInfo=this.proportionalSymbolInfo=a;this._cache.sizeInfo=this._processSizeInfo(a);return this},_processSizeInfo:function(a){return a&&{root:this._createCache(a),minSize:this._createCache(a.minSize),
maxSize:this._createCache(a.maxSize)}},_getVarInfo:function(a,b){var c;a&&a.type===b?(c=e.indexOf(this.visualVariables,a),a=this.visualVariables[c]):(c=b,a=this[b]);return{variable:a,cacheKey:c}},setProportionalSymbolInfo:function(a){this.setSizeInfo(a);return this},getSize:function(a,b){var c=this._getVarInfo(b&&b.sizeInfo,"sizeInfo"),d=c.variable,c=this._cache[c.cacheKey],f=null;if(d)var k=d.minSize,f=d.maxSize,k="object"===typeof k&&k?this._getSize(a,k,c&&c.minSize,b):k,f="object"===typeof f&&
f?this._getSize(a,f,c&&c.maxSize,b):f,f=this._getSize(a,d,c&&c.root,b,[k,f]);return f},_getSize:function(a,b,c,d,f){var k=a.attributes,e=b.field,q=b.expression,g=b.stops,h=0,A=c&&c.exprTree,t=c&&c.ipData,B="number"===typeof a,l=B?a:null;if(e||q||A){var s=d&&d.scale,n=f?f[0]:b.minSize,p=f?f[1]:b.maxSize,u=b.minDataValue,r=b.maxDataValue,v=b.valueUnit||"unknown",C=b.valueRepresentation,z=b.scaleBy,D=b.normalizationField,y=k?parseFloat(k[D]):void 0,w=d&&d.shape;q?l="view.scale"===q.toLowerCase()?s:null:
"number"!==typeof l&&(A?l=this._executeExpr(A,this._createExprContext(a)):m.isFunction(e)?l=e.apply(this,arguments):k&&(l=k[e]));if(null==l||D&&!B&&(isNaN(y)||0===y))return null;!isNaN(y)&&!B&&(l/=y);if(g)p=this._lookupData(l,t),l=p[0],n=p[1],l===n?h=g[l].size:(l=g[l].size,g=g[n].size,h=l+(g-l)*p[2]);else if(null!=n&&null!=p&&null!=u&&null!=r)l<=u?h=n:l>=r?h=p:(g=(l-u)/(r-u),"area"===z&&w?(n=(l="circle"===w)?x*Math.pow(n/2,2):n*n,p=l?x*Math.pow(p/2,2):p*p,g=n+g*(p-n),h=l?2*Math.sqrt(g/x):Math.sqrt(g)):
h=n+g*(p-n));else if("unknown"===v)null!=n&&null!=u&&(n&&u?(g=l/u,h="circle"===w?2*Math.sqrt(g*Math.pow(n/2,2)):"square"===w||"diamond"===w||"image"===w?Math.sqrt(g*Math.pow(n,2)):g*n):h=l+(n||u),h=h<n?n:h,null!=p&&h>p&&(h=p));else{g=(d&&d.resolution?d.resolution:1)*this._meterIn[v];if("area"===C)h=Math.sqrt(l/x)/g,h*=2;else if(h=l/g,"radius"===C||"distance"===C)h*=2;null!=n&&h<n&&(h=n);null!=p&&h>p&&(h=p)}}else h=g&&g[0]&&g[0].size,null==h&&(h=b.minSize);return h=isNaN(h)?0:h},getSizeRangeAtScale:function(a,
b){var c,d=this._getVarInfo(a,"sizeInfo"),f=this._cache[d.cacheKey],k={scale:b};if((a=d.variable)&&b){var e=a.minSize,d=a.maxSize,e="object"===typeof e&&e?this._getSize({},e,f&&f.minSize,k):e,f="object"===typeof d&&d?this._getSize({},d,f&&f.maxSize,k):d;if(null!=e||null!=f)c={minSize:e,maxSize:f}}return c},setColorInfo:function(a){this.colorInfo=a;this._cache.colorInfo=this._processColorInfo(a);return this},_createCache:function(a){return{ipData:this._interpolateData(a),exprTree:this._parseExpr(a&&
a.valueExpression,{vars:{feature:"any"}})}},_processColorInfo:function(a){a&&(e.forEach(a.colors,function(b,c){m.isArray(b)&&(a.colors[c]=new q(b))}),e.forEach(a.stops,function(b,c){b.color&&m.isArray(b.color)&&(a.stops[c].color=new q(b.color))}));return this._createCache(a)},getColor:function(a,b){var c=this._getVarInfo(b&&b.colorInfo,"colorInfo");return this._getColorComponent(a,c.variable,this._cache[c.cacheKey])},setOpacityInfo:function(a){this.opacityInfo=a;this._cache.opacityInfo=this._processOpacityInfo(a);
return this},_processOpacityInfo:function(a){return this._createCache(a)},getOpacity:function(a,b){var c=this._getVarInfo(b&&b.opacityInfo,"opacityInfo");return this._getColorComponent(a,c.variable,this._cache[c.cacheKey],!0)},_getColorComponent:function(a,b,c,d,f){var k=a.attributes,e=b&&b.field,q="number"===typeof a,g=q?a:null,h=c&&c.exprTree,r=c&&c.ipData,t;if(e||h){var s=b.normalizationField,l=k?parseFloat(k[s]):void 0;"number"!==typeof g&&(h?g=this._executeExpr(h,this._createExprContext(a)):
m.isFunction(e)?g=e.apply(this,arguments):k&&(g=k[e]));if(null!=g&&(!s||q||!isNaN(l)&&0!==l))!isNaN(l)&&!q&&(g/=l),t=d?this._getOpacity(g,b,r):this._getColor(g,b,r)}else b&&(k=b.stops,d?(t=k&&k[0]&&k[0].opacity,null==t&&(t=b.opacityValues&&b.opacityValues[0])):t=k&&k[0]&&k[0].color||b.colors&&b.colors[0]);f&&(f.data=g,f.value=t);return f||t},_interpolateData:function(a){var b;if(a)if(a.colors||a.opacityValues){var c=(a.colors||a.opacityValues).length,d=a.minDataValue,f=(a.maxDataValue-d)/(c-1);b=
[];for(a=0;a<c;a++)b[a]=d+a*f}else a.stops&&(b=e.map(a.stops,function(a){return a.value}));return b},_getOpacity:function(a,b,c){a=this._lookupData(a,c);var d;b=b||this.opacityInfo;a&&(c=a[0],d=a[1],c===d?d=this._getOpacValue(b,c):(c=this._getOpacValue(b,c),b=this._getOpacValue(b,d),d=c+(b-c)*a[2]));return d},_getOpacValue:function(a,b){return a.opacityValues?a.opacityValues[b]:a.stops[b].opacity},_getColor:function(a,b,c){a=this._lookupData(a,c);var d;b=b||this.colorInfo;a&&(d=a[0],c=a[1],d=d===
c?this._getColorObj(b,d):q.blendColors(this._getColorObj(b,d),this._getColorObj(b,c),a[2]));return d},_getColorObj:function(a,b){return a.colors?a.colors[b]:a.stops[b].color},_lookupData:function(a,b){var c;if(b){var d=0,f=b.length-1;e.some(b,function(b,c){if(a<b)return f=c,!0;d=c;return!1});c=[d,f,(a-b[d])/(b[f]-b[d])]}return c},_createExprContext:function(a){return{vars:{$feature:v.constructFeature(a)}}},_parseExpr:function(a,b){return a?v.parseScript(a,b):null},_executeExpr:function(a,b){return v.executeScript(a,
b,-1)},_meterIn:{inches:39.3701,feet:3.28084,yards:1.09361,miles:6.21371E-4,"nautical-miles":5.39957E-4,millimeters:1E3,centimeters:100,decimeters:10,meters:1,kilometers:0.0010,"decimal-degrees":180/20015077},_writeSizeInfo:function(a){if(a){a=m.mixin({},a);var b=a.minSize,c=a.maxSize;b&&(a.minSize="number"===typeof b?r.px2pt(b):m.clone(b));c&&(a.maxSize="number"===typeof c?r.px2pt(c):m.clone(c));if(b=a.legendOptions)if(a.legendOptions=m.mixin({},b),b=b.customValues)a.legendOptions.customValues=b.slice(0)}return a},
_writeColorInfo:function(a){a&&(a=m.mixin({},a),a.colors&&(a.colors=e.map(a.colors,function(a){return q.toJsonColor(a)})),a.stops&&(a.stops=e.map(a.stops,function(a){a=m.mixin({},a);a.color&&(a.color=q.toJsonColor(a.color));return a})));return a},_writeOpacityInfo:function(a){var b;a&&(b=m.mixin({},a),b.opacityValues&&(b.transparencyValues=e.map(b.opacityValues,function(a){return 100*(1-a)}),delete b.opacityValues),b.stops&&(b.stops=e.map(b.stops,function(a){a=m.mixin({},a);a.transparency=100*(1-
a.opacity);delete a.opacity;return a})),b.legendOptions&&(b.legendOptions=m.mixin({},b.legendOptions)));return b},toJson:function(){var a=this.visualVariables,b=m.clone(this.authoringInfo),c=this.getVisualVariablesForType("rotationInfo",!1),d=(c=c&&c[0])&&c.field,d=c&&(c.expression||d&&(m.isFunction(d)?d:"["+d+"]"));a&&(a=e.map(a,function(a){"sizeInfo"===a.type?a=this._writeSizeInfo(a):"colorInfo"===a.type?a=this._writeColorInfo(a):"opacityInfo"===a.type?(a=this._writeOpacityInfo(a),a.type="transparencyInfo"):
"rotationInfo"===a.type&&(a=m.mixin({},a));return a},this));b&&e.forEach(b.visualVariables,function(a){"opacityInfo"===a.type&&(a.type="transparencyInfo")});return{rotationType:d&&(this._getRotationType(c)||"geographic"),rotationExpression:d,colorInfo:this._writeColorInfo(this.colorInfo),transparencyInfo:this._writeOpacityInfo(this.opacityInfo),sizeInfo:this._writeSizeInfo(this.sizeInfo),visualVariables:a,authoringInfo:b}}});z("extend-esri")&&m.setObject("renderer.Renderer",s,E);return s});