// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.16/esri/copyright.txt for details.
//>>built
define("esri/renderers/utils","dojo/_base/lang dojo/_base/array dojo/has dojo/date/locale ../kernel ../numberUtils ../Color dojo/i18n!../nls/jsapi dojo/i18n!dojo/cldr/nls/gregorian".split(" "),function(h,f,s,m,t,k,n,u,v){function w(a){return a&&f.map(a,function(a){return new n(a)})}var l={},x={millisecond:0,second:1,minute:2,hour:3,day:4,month:5,year:6},r={millisecond:[{formatLength:"long",selector:"date"},{formatLength:"medium",selector:"time"}],second:[{formatLength:"long",selector:"date"},{formatLength:"medium",
selector:"time"}],minute:[{formatLength:"long",selector:"date"},{formatLength:"short",selector:"time"}],hour:[{formatLength:"long",selector:"date"},{formatLength:"short",selector:"time"}],day:[{formatLength:"long",selector:"date"}],month:[{formatLength:"long",selector:"date"}],year:[{selector:"year"}]};h.mixin(l,{createColorStops:function(a){var b=a.values,d=a.colors,g=a.labelIndexes;a=[];return a=f.map(b,function(a,e){var p="";0===e?p="\x3c ":e===b.length-1&&(p="\x3e ");return{value:a,color:d[e],
label:!g||-1<f.indexOf(g,e)?p+k.format(a):null}})},updateColorStops:function(a){var b=a.stops;a=a.changes;var d=[],g,c=f.map(b,function(a){return a.value});f.forEach(a,function(a){d.push(a.index);c[a.index]=a.value});g=k.round(c,{indexes:d});f.forEach(b,function(a,d){a.value=c[d];var f="";0===d?f="\x3c ":d===b.length-1&&(f="\x3e ");a.label=null!=a.label?f+k.format(g[d]):null})},createClassBreakLabel:function(a){var b=a.minValue,d=a.maxValue,g=a.isFirstBreak?"":"\x3e ";a="percent-of-total"===a.normalizationType?
"%":"";b=null==b?"":k.format(b);d=null==d?"":k.format(d);return g+b+a+" "+u.smartMapping.minToMax+" "+d+a},setLabelsForClassBreaks:function(a){var b=a.classBreaks,d=a.classificationMethod,g=a.normalizationType,c=[];b&&b.length&&("standard-deviation"===d?console.log("setLabelsForClassBreaks: cannot set labels for class breaks generated using 'standard-deviation' method."):a.round?(c.push(b[0].minValue),f.forEach(b,function(a){c.push(a.maxValue)}),c=k.round(c),f.forEach(b,function(a,b){a.label=l.createClassBreakLabel({minValue:0===
b?c[0]:c[b],maxValue:c[b+1],isFirstBreak:0===b,normalizationType:g})})):f.forEach(b,function(a,b){a.label=l.createClassBreakLabel({minValue:a.minValue,maxValue:a.maxValue,isFirstBreak:0===b,normalizationType:g})}))},updateClassBreak:function(a){var b=a.classBreaks,d=a.normalizationType,g=a.change,c=g.index,g=g.value,e=-1,f=-1,h=b.length;"standard-deviation"===a.classificationMethod?console.log("updateClassBreak: cannot update labels for class breaks generated using 'standard-deviation' method."):
(0===c?e=c:c===h?f=c-1:(f=c-1,e=c),-1<e&&e<h&&(a=b[e],a.minValue=g,a.label=l.createClassBreakLabel({minValue:a.minValue,maxValue:a.maxValue,isFirstBreak:0===e,normalizationType:d})),-1<f&&f<h&&(a=b[f],a.maxValue=g,a.label=l.createClassBreakLabel({minValue:a.minValue,maxValue:a.maxValue,isFirstBreak:0===f,normalizationType:d})))},calculateDateFormatInterval:function(a){var b,d,g=a.length,c,e,h,l,k,q,m=Infinity,n;a=f.map(a,function(a){return new Date(a)});for(b=0;b<g-1;b++){c=a[b];h=[];k=Infinity;q=
"";for(d=b+1;d<g;d++)e=a[d],e=c.getFullYear()!==e.getFullYear()&&"year"||c.getMonth()!==e.getMonth()&&"month"||c.getDate()!==e.getDate()&&"day"||c.getHours()!==e.getHours()&&"hour"||c.getMinutes()!==e.getMinutes()&&"minute"||c.getSeconds()!==e.getSeconds()&&"second"||"millisecond",l=x[e],l<k&&(k=l,q=e),h.push(e);k<m&&(m=k,n=q)}return n},createUniqueValueLabel:function(a){var b=a.value,d=a.fieldInfo,g=a.domain;a=a.dateFormatInterval;var c=String(b);if(g=g&&g.codedValues?g.getName(b):null)c=g;else if("number"===
typeof b)if(d&&"esriFieldTypeDate"===d.type){var e=new Date(b);if(a&&r[a])var h=f.map(r[a],function(a){return m.format(e,a)}).reverse(),c=1==h.length?h[0]:v["dateTimeFormat-medium"].replace(/\'/g,"").replace(/\{(\d+)\}/g,function(a,b){return h[b]});else c=m.format(e)}else c=k.format(b);return c},cloneColorInfo:function(a){var b;a&&(b=h.mixin({},a),b.colors=w(b.colors),b.stops=b.stops&&f.map(b.stops,function(a){a=h.mixin({},a);a.color&&(a.color=new n(a.color));return a}));return b},cloneOpacityInfo:function(a){var b;
if(a){b=h.mixin({},a);if(a=b.opacityValues)b.opacityValues=a.slice(0);if(a=b.stops)b.stops=f.map(a,function(a){return h.mixin({},a)});if(a=b.legendOptions)b.legendOptions=h.mixin({},a)}return b},cloneSizeInfo:function(a){var b;if(a){b=h.mixin({},a);b.stops&&(b.stops=f.map(b.stops,function(a){return h.mixin({},a)}));if((a=b.minSize)&&"object"===typeof a)b.minSize=l.cloneSizeInfo(a);if((a=b.maxSize)&&"object"===typeof a)b.maxSize=l.cloneSizeInfo(a);if(a=b.legendOptions)if(b.legendOptions=h.mixin({},
a),a=a.customValues)b.legendOptions.customValues=a.slice(0)}return b}});s("extend-esri")&&h.setObject("renderer.utils",l,t);return l});