// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.16/esri/copyright.txt for details.
//>>built
require({cache:{"esri/tasks/Task":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/json dojo/has ../kernel ../deferredUtils ../urlUtils ../Evented".split(" "),function(A,y,z,F,D,E,G,n){A=A(n,{declaredClass:"esri.tasks._Task",_eventMap:{error:["error"],complete:["result"]},constructor:function(b,a){b&&y.isString(b)&&(this._url=G.urlToObject(this.url=b));a&&a.requestOptions&&(this.requestOptions=a.requestOptions);this.normalization=!0;this._errorHandler=y.hitch(this,this._errorHandler);
this.registerConnectEvents()},_useSSL:function(){var b=this._url,a=/^http:/i;this.url&&(this.url=this.url.replace(a,"https:"));b&&b.path&&(b.path=b.path.replace(a,"https:"))},_encode:function(b,a,e){var d,c,f={},g,k;for(g in b)if("declaredClass"!==g&&(d=b[g],c=typeof d,null!==d&&void 0!==d&&"function"!==c))if(y.isArray(d)){f[g]=[];k=d.length;for(c=0;c<k;c++)f[g][c]=this._encode(d[c])}else"object"===c?d.toJson&&(c=d.toJson(e&&e[g]),"esri.tasks.FeatureSet"===d.declaredClass&&c.spatialReference&&(c.sr=
c.spatialReference,delete c.spatialReference),f[g]=a?c:z.toJson(c)):f[g]=d;return f},_successHandler:function(b,a,e,d){a&&this[a].apply(this,b);e&&e.apply(null,b);d&&E._resDfd(d,b)},_errorHandler:function(b,a,e){this.onError(b);a&&a(b);e&&e.errback(b)},setNormalization:function(b){this.normalization=b},onError:function(){}});F("extend-esri")&&(D.Task=A);return A})},"esri/tasks/QueryTask":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/Deferred dojo/_base/json dojo/has ../kernel ../request ../deferredUtils ../geometry/Extent ../geometry/normalizeUtils ./Task ./FeatureSet".split(" "),
function(A,y,z,F,D,E,G,n,b,a,e,d,c){A=A(d,{declaredClass:"esri.tasks.QueryTask",_eventMap:{complete:["featureSet"],"execute-for-count-complete":["count"],"execute-for-ids-complete":["objectIds"],"execute-relationship-query-complete":["featureSets"]},constructor:function(a,b){this._handler=y.hitch(this,this._handler);this._relationshipQueryHandler=y.hitch(this,this._relationshipQueryHandler);this._executeForIdsHandler=y.hitch(this,this._executeForIdsHandler);this._countHandler=y.hitch(this,this._countHandler);
this._extentHandler=y.hitch(this,this._extentHandler);this.source=b&&b.source;this.gdbVersion=b&&b.gdbVersion;this.registerConnectEvents()},__msigns:[{n:"execute",c:4,a:[{i:0,p:["geometry"]}],e:2},{n:"executeForIds",c:3,a:[{i:0,p:["geometry"]}],e:2},{n:"executeForCount",c:3,a:[{i:0,p:["geometry"]}],e:2},{n:"executeForExtent",c:3,a:[{i:0,p:["geometry"]}],e:2}],onComplete:function(){},onExecuteRelationshipQueryComplete:function(){},onExecuteForIdsComplete:function(){},onExecuteForCountComplete:function(){},
onExecuteForExtentComplete:function(){},execute:function(a,b,c,h,l){var d=l.assembly;a=this._encode(y.mixin({},this._url.query,{f:"json"},a.toJson(d&&d[0])));var m=this._handler,e=this._errorHandler;this.source&&(d={source:this.source.toJson()},a.layer=D.toJson(d));this.gdbVersion&&(a.gdbVersion=this.gdbVersion);return n({url:this._url.path+"/query",content:a,callbackParamName:"callback",load:function(a,h){m(a,h,b,c,l.dfd)},error:function(a){e(a,c,l.dfd)},callbackSuffix:h},this.requestOptions)},executeRelationshipQuery:function(a,
c,d){a=this._encode(y.mixin({},this._url.query,{f:"json"},a.toJson()));var h=this._relationshipQueryHandler,l=this._errorHandler;this.gdbVersion&&(a.gdbVersion=this.gdbVersion);var e=new F(b._dfdCanceller);e._pendingDfd=n({url:this._url.path+"/queryRelatedRecords",content:a,callbackParamName:"callback",load:function(a,b){h(a,b,c,d,e)},error:function(a){l(a,d,e)}},this.requestOptions);return e},executeForIds:function(a,b,c,h){var l=h.assembly;a=this._encode(y.mixin({},this._url.query,{f:"json",returnIdsOnly:!0},
a.toJson(l&&l[0])));var d=this._executeForIdsHandler,m=this._errorHandler;this.source&&(l={source:this.source.toJson()},a.layer=D.toJson(l));this.gdbVersion&&(a.gdbVersion=this.gdbVersion);return n({url:this._url.path+"/query",content:a,callbackParamName:"callback",load:function(a,f){d(a,f,b,c,h.dfd)},error:function(a){m(a,c,h.dfd)}},this.requestOptions)},executeForCount:function(a,b,c,h){var l=h.assembly;a=this._encode(y.mixin({},this._url.query,{f:"json",returnIdsOnly:!0,returnCountOnly:!0},a.toJson(l&&
l[0])));var d=this._countHandler,m=this._errorHandler;this.source&&(l={source:this.source.toJson()},a.layer=D.toJson(l));this.gdbVersion&&(a.gdbVersion=this.gdbVersion);return n({url:this._url.path+"/query",content:a,callbackParamName:"callback",load:function(a,l){d(a,l,b,c,h.dfd)},error:function(a){m(a,c,h.dfd)}},this.requestOptions)},executeForExtent:function(a,b,c,h){var l=h.assembly;a=this._encode(y.mixin({},this._url.query,{f:"json",returnExtentOnly:!0,returnCountOnly:!0},a.toJson(l&&l[0])));
var d=this._extentHandler,m=this._errorHandler;this.source&&(l={source:this.source.toJson()},a.layer=D.toJson(l));this.gdbVersion&&(a.gdbVersion=this.gdbVersion);return n({url:this._url.path+"/query",content:a,callbackParamName:"callback",load:function(a,l){d(a,l,b,c,h.dfd)},error:function(a){m(a,c,h.dfd)}},this.requestOptions)},_handler:function(a,b,d,h,l){try{var e=new c(a);this._successHandler([e],"onComplete",d,l)}catch(m){this._errorHandler(m,h,l)}},_relationshipQueryHandler:function(a,b,d,h,
l){try{var e=a.geometryType,m=a.spatialReference,r={};z.forEach(a.relatedRecordGroups,function(a){var h={};h.geometryType=e;h.spatialReference=m;h.features=a.relatedRecords;h=new c(h);if(null!=a.objectId)r[a.objectId]=h;else for(var b in a)a.hasOwnProperty(b)&&"relatedRecords"!==b&&(r[a[b]]=h)});this._successHandler([r],"onExecuteRelationshipQueryComplete",d,l)}catch(t){this._errorHandler(t,h,l)}},_executeForIdsHandler:function(a,b,c,h,l){try{this._successHandler([a.objectIds],"onExecuteForIdsComplete",
c,l)}catch(d){this._errorHandler(d,h,l)}},_countHandler:function(a,b,c,h,l){try{var d,e=a.features,r=a.objectIds;if(r)d=r.length;else{if(e)throw Error("Unable to perform query. Please check your parameters.");d=a.count}this._successHandler([d],"onExecuteForCountComplete",c,l)}catch(t){this._errorHandler(t,h,l)}},_extentHandler:function(b,c,d,h,l){try{b.extent&&(b.extent=new a(b.extent)),this._successHandler([b],"onExecuteForExtentComplete",d,l)}catch(e){this._errorHandler(e,h,l)}}});e._createWrappers(A);
E("extend-esri")&&y.setObject("tasks.QueryTask",A,G);return A})},"esri/tasks/StatisticDefinition":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/has","../kernel"],function(A,y,z,F){A=A(null,{declaredClass:"esri.tasks.StatisticDefinition",toJson:function(){return{statisticType:this.statisticType,onStatisticField:this.onStatisticField,outStatisticFieldName:this.outStatisticFieldName,maxPointCount:this.maxPointCount,maxRecordCount:this.maxRecordCount,maxVertexCount:this.maxVertexCount}}});
z("extend-esri")&&y.setObject("tasks.StatisticDefinition",A,F);return A})},"esri/layers/labelLayerUtils/StaticLabelClass":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../../kernel ../GraphicsLayer ../../geometry/Extent ../../geometry/Point ../../geometry/Polygon".split(" "),function(A,y,z,F,D,E,G,n){return A(D,{declaredClass:"esri.layers.labelLayerUtils.StaticLabel",constructor:function(){this._preparedLabels=[];this._placedLabels=[];this._extent=null;this._ymax=this._ymin=this._xmax=
this._xmin=0;this._scale=1;this._LINE_STEP_CONST=1.5;this._POLYGON_X_STEP_CONST=1;this._POLYGON_Y_STEP_CONST=0.75;this._OVERRUN=2},setMap:function(b,a){this._labelLayer=a;this._map=b;this._xmin=b.extent.xmin;this._xmax=b.extent.xmax;this._ymin=b.extent.ymin;this._ymax=b.extent.ymax;this._scale=(this._xmax-this._xmin)/b.width},_process:function(b){var a,e,d,c,f,g,k,h,l;this._preparedLabels=b;this._placedLabels=[];for(b=this._preparedLabels.length-1;0<=b;b--){a=this._preparedLabels[b];f=a.labelWidth;
g=a.labelHeight;h=(k=a.options)&&k.lineLabelPlacement?k.lineLabelPlacement:"PlaceAtCenter";l=k&&k.lineLabelPosition?k.lineLabelPosition:"Above";e=k&&k.labelRotation?k.labelRotation:!0;d=a.angle*(Math.PI/180);c=k&&k.howManyLabels?k.howManyLabels:"OneLabel";var p=[];if("point"===a.geometry.type)this._generatePointPositions(a.geometry.x,a.geometry.y,a.text,d,f,g,a.symbolWidth,a.symbolHeight,k,p);else if("multipoint"===a.geometry.type)for(e=0;e<a.geometry.points.length;e++)this._generatePointPositions(a.geometry.points[e][0],
a.geometry.points[e][1],a.text,d,f,g,a.symbolWidth,a.symbolHeight,k,p);else if("polyline"===a.geometry.type)if("PlaceAtStart"===h)this._generateLinePositionsPlaceAtStart(a.geometry,!0,a.text,f,g,2*a.symbolHeight+g,h,l,e,p);else if("PlaceAtEnd"===h)this._generateLinePositionsPlaceAtEnd(a.geometry,!0,a.text,f,g,2*a.symbolHeight+g,h,l,e,p);else{k=[];var m=a.geometry.getExtent(),r=this._map.extent;if(m.getWidth()<f*this._scale/this._OVERRUN&&m.getHeight()<f*this._scale/this._OVERRUN)continue;else 0.5*
m.getWidth()<r.getWidth()&&0.5*m.getHeight()<r.getHeight()?(r=0.1*Math.min(this._map.width,this._map.height)*this._scale,this._generateLinePositionsPlaceAtCenter(a.geometry,!1,r,a.text,f,g,2*a.symbolHeight+g,h,l,e,k)):(r=this._LINE_STEP_CONST*Math.min(this._map.width,this._map.height)*this._scale,this._generateLinePositionsPlaceAtCenter(a.geometry,!0,r,a.text,f,g,2*a.symbolHeight+g,h,l,e,k));this._postSorting(m,k,p)}else if("polygon"===a.geometry.type)for(e=0;e<a.geometry.rings.length;e++)h=a.geometry.rings[e],
n.prototype.isClockwise(h)&&(l=this._calcRingExtent(h),l.xmax-l.xmin<4*f*this._scale/this._OVERRUN&&l.ymax-l.ymin<4*g*this._scale/this._OVERRUN||this._generatePolygonPositionsForManyLabels(h,a.geometry.spatialReference,a.text,d,f,g,p));for(e=0;e<p.length&&!(h=p[e].x,l=p[e].y,void 0!==p[e].angle&&(d=p[e].angle),k=this._findPlace(a,a.text,h,l,d,f,g),"OneLabel"===c&&k&&this._labelLayer._isWithinScreenArea(new G(h,l,a.geometry.spatialReference)));e++);}return this._placedLabels},_generatePointPositions:function(b,
a,e,d,c,f,g,k,h,l){e=h&&h.pointPriorities?h.pointPriorities:"AboveRight";c=(g+c)*this._scale;f=(k+f)*this._scale;switch(e.toLowerCase()){case "aboveleft":b-=c;a+=f;break;case "abovecenter":a+=f;break;case "aboveright":b+=c;a+=f;break;case "centerleft":b-=c;break;case "centercenter":break;case "centerright":b+=c;break;case "belowleft":b-=c;a-=f;break;case "belowcenter":a-=f;break;case "belowright":b+=c;a-=f;break;default:return}l.push({x:b,y:a})},_generateLinePositionsPlaceAtStart:function(b,a,e,d,
c,f,g,k,h,l){g=d*this._scale;var p=this._LINE_STEP_CONST*Math.min(this._map.width,this._map.height)*this._scale,m,r,t,s,x,q,u,v;for(m=0;m<b.paths.length;m++){var w=b.paths[m],C=g,B=0;for(r=0;r<w.length-1;r++)t=w[r][0],s=w[r][1],x=w[r+1][0],q=w[r+1][1],u=x-t,v=q-s,u=Math.sqrt(u*u+v*v),B+u>C?(B=this._generatePositionsOnLine(b.spatialReference,a,C,p,B,t,s,x,q,e,d,c,f,k,h,l),C=p):B+=u}},_generateLinePositionsPlaceAtEnd:function(b,a,e,d,c,f,g,k,h,l){g=d*this._scale;var p=this._LINE_STEP_CONST*Math.min(this._map.width,
this._map.height)*this._scale,m,r,t,s,x,q,u,v;for(m=0;m<b.paths.length;m++){var w=b.paths[m],C=g,B=0;for(r=w.length-2;0<=r;r--)t=w[r+1][0],s=w[r+1][1],x=w[r][0],q=w[r][1],u=x-t,v=q-s,u=Math.sqrt(u*u+v*v),B+u>C?(B=this._generatePositionsOnLine(b.spatialReference,a,C,p,B,t,s,x,q,e,d,c,f,k,h,l),C=p):B+=u}},_generateLinePositionsPlaceAtCenter:function(b,a,e,d,c,f,g,k,h,l,p){var m,r,t,s,x,q,u,v;for(k=0;k<b.paths.length;k++){var w=b.paths[k];if(!(2>w.length)){var C=0;for(m=0;m<w.length-1;m++)t=w[m][0],
s=w[m][1],x=w[m+1][0],q=w[m+1][1],u=x-t,v=q-s,C+=Math.sqrt(u*u+v*v);var B=0;for(m=0;m<w.length-1;m++){t=w[m][0];s=w[m][1];x=w[m+1][0];q=w[m+1][1];u=x-t;v=q-s;u=Math.sqrt(u*u+v*v);if(B+u>C/2)break;B+=u}m==w.length-1&&m--;t=w[m][0];s=w[m][1];x=w[m+1][0];q=w[m+1][1];u=x-t;v=q-s;B=C/2-B;v=Math.atan2(v,u);u=t+B*Math.cos(v);v=s+B*Math.sin(v);t=this._angleAndShifts(t,s,x,q,g,h,l);p.push({x:u+t.shiftX,y:v+t.shiftY,angle:t.angle});var C=u,n=v,B=0;for(r=m;r<w.length-1;r++)r==m?(t=C,s=n):(t=w[r][0],s=w[r][1]),
x=w[r+1][0],q=w[r+1][1],u=x-t,v=q-s,u=Math.sqrt(u*u+v*v),B=B+u>e?this._generatePositionsOnLine(b.spatialReference,a,e,e,B,t,s,x,q,d,c,f,g,h,l,p):B+u;B=0;for(r=m;0<=r;r--)r==m?(t=C,s=n):(t=w[r+1][0],s=w[r+1][1]),x=w[r][0],q=w[r][1],u=x-t,v=q-s,u=Math.sqrt(u*u+v*v),B=B+u>e?this._generatePositionsOnLine(b.spatialReference,a,e,e,B,t,s,x,q,d,c,f,g,h,l,p):B+u}}},_generatePositionsOnLine:function(b,a,e,d,c,f,g,k,h,l,p,m,r,t,s,n){l=Math.atan2(h-g,k-f);p=f;m=g;var q=p,u=m;do if(c=e-c,p+=c*Math.cos(l),m+=c*
Math.sin(l),this._belongs(p,m,f,g,k,h))c=this._angleAndShifts(f,g,k,h,r,t,s),e=p+c.shiftX,u=m+c.shiftY,a?this._labelLayer._isWithinScreenArea(new E(e,u,e,u,b))&&n.push({x:e,y:u,angle:c.angle}):n.push({x:e,y:u,angle:c.angle}),q=p,u=m,c=0,e=d;else return b=k-q,h-=u,Math.sqrt(b*b+h*h);while(1)},_postSorting:function(b,a,e){if(b&&0<a.length){var d=0.5*(b.xmin+b.xmax);b=0.5*(b.ymin+b.ymax);for(var c=a[0].x,f=a[0].y,g=Math.sqrt((c-d)*(c-d)+(f-b)*(f-b)),k=a[0].angle,h=0;h<a.length;h++){var l=a[h].x,p=a[h].y,
m=Math.sqrt((l-d)*(l-d)+(p-b)*(p-b));m<g&&(c=l,f=p,g=m,k=a[h].angle)}e.push({x:c,y:f,angle:k})}},_belongs:function(b,a,e,d,c,f){if(c==e&&f==d)return!1;if(c>e){if(b>c||b<e)return!1}else if(b<c||b>e)return!1;if(f>d){if(a>f||a<d)return!1}else if(a<f||a>d)return!1;return!0},_angleAndShifts:function(b,a,e,d,c,f,g){for(b=Math.atan2(d-a,e-b);b>Math.PI/2;)b-=Math.PI;for(;b<-(Math.PI/2);)b+=Math.PI;d=Math.sin(b);var k=Math.cos(b);e=a=0;"Above"==f&&(a=c*d*this._scale,e=c*k*this._scale);"Below"==f&&(a=-c*d*
this._scale,e=-c*k*this._scale);c=[];c.angle=g?-b:0;c.shiftX=-a;c.shiftY=e;return c},_generatePolygonPositionsForManyLabels:function(b,a,e,d,c,f,g){d=this._calcRingExtent(b);if(0.75*(d.xmax-d.xmin)>this._map.width*this._scale||0.75*(d.ymax-d.ymin)>this._map.height*this._scale){var k=this._findCentroidForRing(b);f=this._map.width*this._scale<d.xmax-d.xmin?this._POLYGON_X_STEP_CONST*this._map.width*this._scale:this._POLYGON_X_STEP_CONST*(d.xmax-d.xmin);c=this._map.height*this._scale<d.ymax-d.ymin?this._POLYGON_Y_STEP_CONST*
this._map.height*this._scale:this._POLYGON_Y_STEP_CONST*(d.ymax-d.ymin);var h=k[0]-Math.round((k[0]-d.xmin)/f)*f,l=k[1]-Math.round((k[1]-d.ymin)/c)*c,p,k=!0;for(p=l;p<d.ymax;p+=c)if(k=!k,!(p<this._ymin||p>this._ymax))for(l=h+(k?0:f/2);l<d.xmax;l+=f)this._labelLayer._isWithinScreenArea(new E(l,p,l,p,a))&&this._isPointWithinRing(e,b,l,p)&&g.push({x:l,y:p})}else{k=this._findCentroidForRing(b);for(d=0;10>d;d++)if(c=k[0],h=k[1]+(d%2?-1:1)*Math.floor(d/2)*f*this._scale,this._labelLayer._isWithinScreenArea(new E(c,
h,c,h,a))&&this._isPointWithinRing(e,b,c,h)){g.push({x:c,y:h});break}}},_calcRingExtent:function(b){var a,e;e=new E;for(a=0;a<b.length-1;a++){var d=b[a][0],c=b[a][1];if(void 0===e.xmin||d<e.xmin)e.xmin=d;if(void 0===e.ymin||c<e.ymin)e.ymin=c;if(void 0===e.xmax||d>e.xmax)e.xmax=d;if(void 0===e.ymax||c>e.ymax)e.ymax=c}return e},_isPointWithinPolygon:function(b,a,e,d){var c;for(c=0;c<a.rings.length;c++)if(this._isPointWithinRing(b,a.rings[c],e,d))return!0;return!1},_isPointWithinRing:function(b,a,e,
d){var c,f,g,k,h=[],l=a.length;for(b=0;b<l-1;b++)if(c=a[b][0],f=a[b][1],g=a[b+1][0],k=a[b+1][1],!(c==g&&f==k)){if(f==k)if(d==f)h.push(c);else continue;c==g?(f<k&&(d>=f&&d<k)&&h.push(c),f>k&&(d<=f&&d>k)&&h.push(c)):(f=(g-c)/(k-f)*(d-f)+c,c<g&&(f>=c&&f<g)&&h.push(f),c>g&&(f<=c&&f>g)&&h.push(f))}h.sort(function(a,h){return a-h});for(b=0;b<h.length-1;b++)if(c=h[b],g=h[b+1],e>=c&&e<g)if(b%2)break;else return!0;return!1},_findCentroidForRing:function(b){for(var a=b.length,e=[0,0],d=0,c=b[0][0],f=b[0][1],
g=1;g<a-1;g++){var k=b[g][0],h=b[g][1],l=b[g+1][0],p=b[g+1][1],m=(k-c)*(p-f)-(l-c)*(h-f);e[0]+=m*(c+k+l);e[1]+=m*(f+h+p);d+=m}e[0]/=3*d;e[1]/=3*d;return e},_findCentroidForFeature:function(b){for(var a=0,e=[0,0],d=0;d<b.rings.length;d++)for(var c=b.rings[d],f=c.length,g=c[0][0],k=c[0][1],h=1;h<f-1;h++){var l=c[h][0],p=c[h][1],m=c[h+1][0],r=c[h+1][1],t=(l-g)*(r-k)-(m-g)*(p-k);e[0]+=t*(g+l+m);e[1]+=t*(k+p+r);a+=t}e[0]/=3*a;e[1]/=3*a;return e},_findPlace:function(b,a,e,d,c,f,g){if(isNaN(e)||isNaN(d))return!1;
for(var k=0;k<this._placedLabels.length;k++){var h=this._placedLabels[k].angle,l=this._placedLabels[k].width*this._scale,p=this._placedLabels[k].height*this._scale,m=this._placedLabels[k].x-e,r=this._placedLabels[k].y-d;if(0===c&&0===h){if(this._findPlace2(-f*this._scale,-g*this._scale,f*this._scale,g*this._scale,m-l,r-p,m+l,r+p))return!1}else{var t=new E(-f*this._scale,-g*this._scale,f*this._scale,g*this._scale,null),s=0,x=1;0!==c&&(s=Math.sin(c),x=Math.cos(c));var q=m*x-r*s,m=m*s+r*x,h=h-c,s=Math.sin(h),
x=Math.cos(h),u=-l*x- -p*s,r=-l*s+-p*x,h=+l*x- -p*s,v=+l*s+-p*x,l=q+u,p=m-r,s=q+h,x=m-v,u=q-u,r=m+r,q=q-h,m=m+v,h=new n;h.addRing([[l,p],[s,x],[u,r],[q,m],[l,p]]);if(t.intersects(h))return!1}}for(;c>Math.PI/2;)c-=Math.PI;for(;c<-(Math.PI/2);)c+=Math.PI;k={};k.layer=b;k.text=a;k.angle=c;k.x=e;k.y=d;k.width=f;k.height=g;this._placedLabels.push(k);return!0},_findPlace2:function(b,a,e,d,c,f,g,k){return(b>=c&&b<=g||e>=c&&e<=g||b<=c&&e>=g)&&(a>=f&&a<=k||d>=f&&d<=k||a<=f&&d>=k)?!0:!1}})})},"esri/layers/labelLayerUtils/DynamicLabelClass":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../../kernel ../GraphicsLayer ../../geometry/Extent ../../geometry/Polygon".split(" "),
function(A,y,z,F,D,E,G){A=A(D,{declaredClass:"esri.layers.labelLayerUtils.DynamicLabelClass",constructor:function(){this._preparedLabels=[];this._placedLabels=[];this._extent=null;this._y1=this._x1=this._y0=this._x0=this._ymax=this._ymin=this._xmax=this._xmin=0;this._scale=1},setMap:function(n,b){this._labelLayer=b;this._xmin=n.extent.xmin;this._xmax=n.extent.xmax;this._ymin=n.extent.ymin;this._ymax=n.extent.ymax;this._scale=(this._xmax-this._xmin)/n.width},_process:function(n){this._preparedLabels=
n;this._placedLabels=[];var b;for(n=this._preparedLabels.length-1;0<=n;n--){var a=this._preparedLabels[n],e=Math.min(a.labelWidth,a.labelHeight),d=a.labelWidth+0*e,e=a.labelHeight+0*e,c=(b=a.options)&&void 0!==b.lineLabelPlacement?b.lineLabelPlacement:"PlaceAtCenter",f=b&&void 0!==b.lineLabelPosition?b.lineLabelPosition:"Above",g=b&&void 0!==b.pointPriorities?b.pointPriorities:"AboveRight",k=[2,2,1,3,0,2,3,3,2];"AboveLeft"==g?k=[1,2,2,2,0,3,2,3,3]:"AboveCenter"==g?k=[2,1,2,2,0,2,3,3,3]:"AboveRight"==
g?k=[2,2,1,3,0,2,3,3,2]:"CenterLeft"==g?k=[2,2,3,1,0,3,2,2,3]:"CenterCenter"==g?k=[0,0,0,0,1,0,0,0,0]:"CenterRight"==g?k=[3,2,2,3,0,1,3,2,2]:"BelowLeft"==g?k=[2,3,3,2,0,3,1,2,2]:"BelowCenter"==g?k=[3,3,3,2,0,2,2,1,2]:"BelowRight"==g&&(k=[3,3,2,3,0,2,2,2,1]);var h=b&&void 0!==b.labelRotation?b.labelRotation:!0,g=a.angle*(Math.PI/180);b=b&&void 0!==b.howManyLabels?b.howManyLabels:"OneLabel";if("point"==a.geometry.type)this._generatePointPositions(a,a.geometry.x,a.geometry.y,a.text,g,d,e,a.symbolWidth,
a.symbolHeight,k);else if("multipoint"==a.geometry.type){c=a.geometry;for(f=0;f<c.points.length;f++)this._generatePointPositions(a,c.points[f][0],c.points[f][1],a.text,g,d,e,a.symbolWidth,a.symbolHeight,k)}else"polyline"==a.geometry.type?this._generateLinePositions(a,a.geometry,a.text,d,e,2*a.symbolHeight+e,c,f,h):"polygon"==a.geometry.type&&this._generatePolygonPositions(a,b,a.geometry,a.text,g,d,e)}return this._placedLabels},_generatePointPositions:function(n,b,a,e,d,c,f,g,k,h){g=(g+c)*this._scale;
k=(k+f)*this._scale;var l,p;for(l=1;3>=l;l++)for(p=1;9>=p;p++)if(h[p-1]==l)switch(p){case 1:if(this._findPlace(n,e,b-g,a+k,d,c,f))return;break;case 2:if(this._findPlace(n,e,b,a+k,d,c,f))return;break;case 3:if(this._findPlace(n,e,b+g,a+k,d,c,f))return;break;case 4:if(this._findPlace(n,e,b-g,a,d,c,f))return;break;case 5:if(this._findPlace(n,e,b,a,d,c,f))return;break;case 6:if(this._findPlace(n,e,b+g,a,d,c,f))return;break;case 7:if(this._findPlace(n,e,b-g,a-k,d,c,f))return;break;case 8:if(this._findPlace(n,
e,b,a-k,d,c,f))return;break;case 9:if(this._findPlace(n,e,b+g,a-k,d,c,f))return}},_generateLinePositions:function(n,b,a,e,d,c,f,g,k){var h=e*this._scale*e*this._scale,l,p,m;for(l=0;l<b.paths.length;l++){var r=b.paths[l],t=r.length,s=Math.floor((t-1)/2),x=0!==(t-1)%2?1:-1;"PlaceAtStart"==f&&(s=0,x=1);"PlaceAtEnd"==f&&(s=t-2,x=-1);for(;0<=s&&s<t-1;){for(p=s;p<t;p++){var q=r[s][0],u=r[s][1],v=r[p][0]-q,w=r[p][1]-u;if(v*v+w*w>h){for(var C=Math.atan2(w,v);C>Math.PI/2;)C-=Math.PI;for(;C<-(Math.PI/2);)C+=
Math.PI;var B=Math.sin(C),I=Math.cos(C),H=0,y=0;"Above"==g&&(H=c*B*this._scale,y=c*I*this._scale);"Below"==g&&(H=-c*B*this._scale,y=-c*I*this._scale);if(1==p-s){if(this._clipLine(q,u,r[p][0],r[p][1])&&(q=this._x1-this._x0,m=this._y1-this._y0,q*q+m*m>h&&(p=Math.atan2(m,q),v=e/2+2*d,u=v*this._scale*Math.cos(p),v=v*this._scale*Math.sin(p),"PlaceAtStart"==f?(q=this._x0+u,m=this._y0+v):"PlaceAtEnd"==f?(q=this._x1-u,m=this._y1-v):(q=this._x0+q/2,m=this._y0+m/2),this._findPlace(n,a,q-H,m+y,k?-p:0,e,d))))return}else{var z=
0;for(m=s;m<=p;m++)z=Math.max(z,Math.abs((r[m][1]-u)*I-(r[m][0]-q)*B));if(z<d&&this._findPlace(n,a,q+v/2-H,u+w/2+y,k?-C:0,e,d))return}break}}s+=x}}},_generatePolygonPositions:function(n,b,a,e,d,c,f){var g;if("ManyLabels"==b)for(b=0;b<a.rings.length;b++)g=a.rings[b],G.prototype.isClockwise(g)&&(g=this._findCentroid(g,this._xmin,this._ymin,this._xmax,this._ymax),this._findPlace(n,e,g[0],g[1],d,c,f));else{g=this._findCentroidForFeature(a,this._xmin,this._ymin,this._xmax,this._ymax);var k=g[1],h=0;for(b=
0;10>b;b++){h+=f/4;g=this._findCentroidForFeature(a,this._xmin,k+(h-f/4),this._xmax,k+(h+f/4));if(this._findPlace(n,e,g[0],g[1],d,c,f))break;g=this._findCentroidForFeature(a,this._xmin,k-(h+f/4),this._xmax,k-(h-f/4));if(this._findPlace(n,e,g[0],g[1],d,c,f))break}}},_findCentroid:function(n,b,a,e,d){var c=n.length,f=[0,0],g=0,k=n[0][0],h=n[0][1];k>e&&(k=e);k<b&&(k=b);h>d&&(h=d);h<a&&(h=a);for(var l=1;l<c-1;l++){var p=n[l][0],m=n[l][1],r=n[l+1][0],t=n[l+1][1];p>e&&(p=e);p<b&&(p=b);m>d&&(m=d);m<a&&(m=
a);r>e&&(r=e);r<b&&(r=b);t>d&&(t=d);t<a&&(t=a);var s=(p-k)*(t-h)-(r-k)*(m-h);f[0]+=s*(k+p+r);f[1]+=s*(h+m+t);g+=s}f[0]/=3*g;f[1]/=3*g;if(isNaN(f[0])||isNaN(f[1]))return f;a=[];this._fillBuffer(n,a,f);f[0]=this._sortBuffer(a,f[0],b,e);return f},_findCentroidForFeature:function(n,b,a,e,d){for(var c,f=0,g=[0,0],k=0;k<n.rings.length;k++){var h=n.rings[k],l=h.length,p=h[0][0],m=h[0][1];p>e&&(p=e);p<b&&(p=b);m>d&&(m=d);m<a&&(m=a);for(c=1;c<l-1;c++){var r=h[c][0],t=h[c][1],s=h[c+1][0],x=h[c+1][1];r>e&&(r=
e);r<b&&(r=b);t>d&&(t=d);t<a&&(t=a);s>e&&(s=e);s<b&&(s=b);x>d&&(x=d);x<a&&(x=a);var q=(r-p)*(x-m)-(s-p)*(t-m);g[0]+=q*(p+r+s);g[1]+=q*(m+t+x);f+=q}}g[0]/=3*f;g[1]/=3*f;if(isNaN(g[0])||isNaN(g[1]))return g;a=[];for(c=0;c<n.rings.length;c++)this._fillBuffer(n.rings[c],a,g);g[0]=this._sortBuffer(a,g[0],b,e);return g},_fillBuffer:function(n,b,a){for(var e=n.length-1,d=n[0][1]>=n[e][1]?1:-1,c=0;c<=e;c++){var f=c,g=c+1;c==e&&(g=0);var k=n[f][0],f=n[f][1],h=n[g][0],g=n[g][1],l=g>=f?1:-1;if(f<=a[1]&&a[1]<=
g||g<=a[1]&&a[1]<=f)a[1]!=f&&a[1]!=g?(b.push((a[1]-f)*(h-k)/(g-f)+k),d=l):a[1]==f&&a[1]!=g?(d!=l&&b.push(k),d=l):a[1]!=f&&a[1]==g?(b.push(h),d=l):a[1]==f&&a[1]==g&&(1==d&&b.push(k),b.push(h),d=l)}},_sortBuffer:function(n,b,a,e){var d=n.length;n.sort();if(0<d){for(var c=0,f=b=0;f<d-1;f+=2){var g=Math.abs(n[f+1]-n[f]);!(n[f]<=a&&n[f+1]<=a)&&(!(n[f]>=e&&n[f+1]>=e)&&g>c)&&(c=g,b=f)}d=n[b];n=n[b+1];d>e&&(d=e);d<a&&(d=a);n>e&&(n=e);n<a&&(n=a);b=(d+n)/2}return b},_findPlace:function(n,b,a,e,d,c,f){if(isNaN(a)||
isNaN(e))return!1;for(var g=0;g<this._placedLabels.length;g++){var k=this._placedLabels[g].angle,h=this._placedLabels[g].width*this._scale,l=this._placedLabels[g].height*this._scale,p=this._placedLabels[g].x-a,m=this._placedLabels[g].y-e;if(0===d&&0===k){if(this._findPlace2(-c*this._scale,-f*this._scale,c*this._scale,f*this._scale,p-h,m-l,p+h,m+l))return!1}else{var r=new E(-c*this._scale,-f*this._scale,c*this._scale,f*this._scale,null),t=0,s=1;0!==d&&(t=Math.sin(d),s=Math.cos(d));var x=p*s-m*t,p=
p*t+m*s,k=k-d,t=Math.sin(k),s=Math.cos(k),q=-h*s- -l*t,m=-h*t+-l*s,k=+h*s- -l*t,u=+h*t+-l*s,h=x+q,l=p-m,t=x+k,s=p-u,q=x-q,m=p+m,x=x-k,p=p+u,k=new G;k.addRing([[h,l],[t,s],[q,m],[x,p],[h,l]]);if(r.intersects(k))return!1}}for(;d>Math.PI/2;)d-=Math.PI;for(;d<-(Math.PI/2);)d+=Math.PI;g={};g.layer=n;g.text=b;g.angle=d;g.x=a;g.y=e;g.width=c;g.height=f;this._placedLabels.push(g);return!0},_findPlace2:function(n,b,a,e,d,c,f,g){return(n>=d&&n<=f||a>=d&&a<=f||n<=d&&a>=f)&&(b>=c&&b<=g||e>=c&&e<=g||b<=c&&e>=
g)?!0:!1},_clipLine:function(n,b,a,e){for(var d=this._code(n,b),c=this._code(a,e);0!==d||0!==c;){if(0!==(d&c))return!1;var f=a-n,g=e-b;0!==d?(n<this._xmin?(b+=g*(this._xmin-n)/f,n=this._xmin):n>this._xmax?(b+=g*(this._xmax-n)/f,n=this._xmax):b<this._ymin?(n+=f*(this._ymin-b)/g,b=this._ymin):b>this._ymax&&(n+=f*(this._ymax-b)/g,b=this._ymax),d=this._code(n,b)):(a<this._xmin?(e+=g*(this._xmin-a)/f,a=this._xmin):a>this._xmax?(e+=g*(this._xmax-a)/f,a=this._xmax):e<this._ymin?(a+=f*(this._ymin-e)/g,e=
this._ymin):e>this._ymax&&(a+=f*(this._ymax-e)/g,e=this._ymax),c=this._code(a,e))}this._x0=n;this._y0=b;this._x1=a;this._y1=e;return!0},_code:function(n,b){var a=0;n<this._xmin&&(a+=8);n>this._xmax&&(a+=4);b<this._ymin&&(a+=2);b>this._ymax&&(a+=1);return a}});z("extend-esri")&&y.setObject("layers.labelLayerUtils.DynamicLabelClass",A,F);return A})},"esri/tasks/FeatureSet":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has ../kernel ../lang ../graphic ../SpatialReference ../graphicsUtils ../geometry/jsonUtils ../symbols/jsonUtils".split(" "),
function(A,y,z,F,D,E,G,n,b,a,e){A=A(null,{declaredClass:"esri.tasks.FeatureSet",constructor:function(b){if(b){y.mixin(this,b);var c=this.features,f=b.spatialReference,g=a.getGeometryType(b.geometryType),f=this.spatialReference=new n(f);this.geometryType=b.geometryType;b.fields&&(this.fields=b.fields);z.forEach(c,function(a,h){var b=a.geometry&&a.geometry.spatialReference;c[h]=new G(g&&a.geometry?new g(a.geometry):null,a.symbol&&e.fromJson(a.symbol),a.attributes);c[h].geometry&&!b&&c[h].geometry.setSpatialReference(f)});
this._hydrate()}else this.features=[]},displayFieldName:null,geometryType:null,spatialReference:null,fieldAliases:null,toJson:function(d){var c={};this.displayFieldName&&(c.displayFieldName=this.displayFieldName);this.fields&&(c.fields=this.fields);this.spatialReference?c.spatialReference=this.spatialReference.toJson():this.features[0]&&this.features[0].geometry&&(c.spatialReference=this.features[0].geometry.spatialReference.toJson());this.features[0]&&(this.features[0].geometry&&(c.geometryType=
a.getJsonType(this.features[0].geometry)),c.features=b._encodeGraphics(this.features,d));c.exceededTransferLimit=this.exceededTransferLimit;c.transform=this.transform;return E.fixJson(c)},_hydrate:function(){var a=this.transform,b=this.geometryType;if(a&&b)for(var e=this.features,g=a.translate[0],k=a.translate[1],h=a.scale[0],l=a.scale[1],p=function(a,h,b){if("esriGeometryPoint"===a)return function(a){a.x=h(a.x);a.y=b(a.y)};if("esriGeometryPolyline"===a||"esriGeometryPolygon"===a)return function(a){a=
a.rings||a.paths;var c,q,l,e,d,m,f,g;c=0;for(q=a.length;c<q;c++){d=a[c];l=0;for(e=d.length;l<e;l++)m=d[l],0<l?(f+=m[0],g+=m[1]):(f=m[0],g=m[1]),m[0]=h(f),m[1]=b(g)}};if("esriGeometryEnvelope"===a)return function(a){a.xmin=h(a.xmin);a.ymin=b(a.ymin);a.xmax=h(a.xmax);a.ymax=b(a.ymax)};if("esriGeometryMultipoint"===a)return function(a){a=a.points;var c,q,l,e,d;c=0;for(q=a.length;c<q;c++)l=a[c],0<c?(e+=l[0],d+=l[1]):(e=l[0],d=l[1]),l[0]=h(e),l[1]=b(d)}}(b,function(a){return a*h+g},function(a){return k-
a*l}),a=0,b=e.length;a<b;a++)e[a].geometry&&p(e[a].geometry);this.transform=null},quantize:function(a){if(!this.geometryType)return this.transform=null,this;var b=a.translate[0],e=a.translate[1],g=a.scale[0],k=a.scale[1],h=this.features,l=function(a,h,b){var q,c,l,e,d,m,f=[];q=0;for(c=a.length;q<c;q++)if(l=a[q],0<q){if(m=h(l[0]),l=b(l[1]),m!==e||l!==d)f.push([m-e,l-d]),e=m,d=l}else e=h(l[0]),d=b(l[1]),f.push([e,d]);return 0<f.length?f:null},p=function(a,h,b){if("esriGeometryPoint"===a)return function(a){a.x=
h(a.x);a.y=b(a.y);return a};if("esriGeometryPolyline"===a||"esriGeometryPolygon"===a)return function(a){var c,e,d,m,f;d=a.rings||a.paths;f=[];c=0;for(e=d.length;c<e;c++)m=d[c],(m=l(m,h,b))&&f.push(m);return 0<f.length?(a.rings?a.rings=f:a.paths=f,a):null};if("esriGeometryMultipoint"===a)return function(a){var c;c=l(a.points,h,b);return 0<c.length?(a.points=c,a):null};if("esriGeometryEnvelope"===a)return function(a){return a}}(this.geometryType,function(a){return Math.round((a-b)/g)},function(a){return Math.round((e-
a)/k)}),m,r;m=0;for(r=h.length;m<r;m++)h[m].geometry&&(p(h[m].geometry)||h[m].setGeometry(null));this.transform=a;return this}});F("extend-esri")&&y.setObject("tasks.FeatureSet",A,D);return A})},"esri/PopupInfo":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/json dojo/i18n dojo/has dojo/Deferred dojo/sniff dojo/promise/all ./lang ./kernel ./request ./tasks/query ./tasks/QueryTask ./tasks/StatisticDefinition dojo/i18n!dojo/cldr/nls/number".split(" "),function(A,y,
z,F,D,E,G,n,b,a,e,d,c,f,g,k){A=A(null,{declaredClass:"esri.PopupInfo",initialize:function(a,b){if(a){y.mixin(this,b);this.info=a;this.title=this.getTitle;this.content=this.getContent;var c=this._fieldLabels={},e=this._fieldsMap={};a.fieldInfos&&z.forEach(a.fieldInfos,function(a){var b=a.fieldName.toLowerCase();c[b]=a.label;e[b]=a});this._relatedFieldPrefix="relationships/";this.titleHasRelatedFields=!!(a.title&&-1!==a.title.indexOf("{"+this._relatedFieldPrefix))}},toJson:function(){return F.fromJson(F.toJson(this.info))},
getTitle:function(){},getContent:function(){},getFieldInfo:function(a){var b;z.some(this.info&&this.info.fieldInfos,function(c){c.fieldName===a&&(b=c);return!!b});return b},getComponents:function(a){var b=this.info,c=new G,e,d;b.fieldInfos&&(d=z.filter(b.fieldInfos,function(a){return-1!==a.fieldName.indexOf(this._relatedFieldPrefix)},this));d&&0<d.length&&(e=this._getRelatedRecords({graphic:a,fieldsInfo:d}));e?e.always(y.hitch(this,function(){c.resolve(this._getPopupValues(a))})):c.resolve(this._getPopupValues(a));
return c.promise},getAttachments:function(a){var b=a.getLayer();a=a.attributes;if(this.info.showAttachments&&(b&&b.hasAttachments&&b.objectIdField)&&(a=a&&a[b.objectIdField]))return b.queryAttachmentInfos(a)},_getPopupValues:function(b,c){var e=this.info,d=b.getLayer(),f=y.clone(b.attributes)||{},g=y.clone(f),k=e.fieldInfos,n="",q="",u,v,w,C,B,I=d&&d._getDateOpts&&d._getDateOpts().properties,I=I&&I.slice(0),H={dateFormat:{properties:I,formatter:"DateFormat"+this._insertOffset(this._dateFormats.shortDateShortTime)}};
if(this._relatedInfo)for(C in this._relatedInfo)if(this._relatedInfo.hasOwnProperty(C)){var A=this._relatedInfo[C],E=this._relatedLayersInfo[C];A&&(z.forEach(A.relatedFeatures,function(a){for(B in a.attributes)if(a.attributes.hasOwnProperty(B)&&"esriRelCardinalityOneToOne"===E.relation.cardinality){var b=this._toRelatedFieldName([E.relation.id,B]);f[b]=g[b]=a.attributes[B]}},this),z.forEach(A.relatedStatsFeatures,function(a){for(B in a.attributes)if(a.attributes.hasOwnProperty(B)){var b=this._toRelatedFieldName([E.relation.id,
B]);f[b]=g[b]=a.attributes[B]}},this))}k&&z.forEach(k,function(a){v=a.fieldName;var b=this._getLayerFieldInfo(d,v);b&&(v=a.fieldName=b.name);g[v]=this._formatValue(g[v],v,H);I&&(a.format&&a.format.dateFormat)&&(a=z.indexOf(I,v),-1<a&&I.splice(a,1))},this);if(d){C=d.types;var G=(A=d.typeIdField)&&f[A];for(v in f)if(f.hasOwnProperty(v)&&-1===v.indexOf(this._relatedFieldPrefix)&&(w=f[v],a.isDefined(w))){var D=this._getDomainName(d,b,C,G,v,w);a.isDefined(D)?g[v]=D:v===A&&(D=this._getTypeName(d,b,w),a.isDefined(D)&&
(g[v]=D))}}e.title&&(n=this._processFieldsInLinks(this._fixTokens(e.title,d),f),n=y.trim(a.substitute(g,n,H)||""));if(c)return{title:n};e.description&&(q=this._processFieldsInLinks(this._fixTokens(e.description,d),f),q=y.trim(a.substitute(g,q,H)||""));k&&(u=[],z.forEach(k,function(b){(v=b.fieldName)&&b.visible&&u.push([b.label||v,a.substitute(g,"${"+v+"}",H)||""])}));var F,J;e.mediaInfos&&(F=[],z.forEach(e.mediaInfos,function(b){J=0;w=b.value;switch(b.type){case "image":var h=w.sourceURL,h=h&&y.trim(a.substitute(f,
this._fixTokens(h,d)));J=!!h;break;case "piechart":case "linechart":case "columnchart":case "barchart":var c,h=w.normalizeField;w.fields=z.map(w.fields,function(a){return(c=this._getLayerFieldInfo(d,a))?c.name:a},this);h&&(c=this._getLayerFieldInfo(d,h),w.normalizeField=c?c.name:h);J=z.some(w.fields,function(b){return a.isDefined(f[b])||-1!==b.indexOf(this._relatedFieldPrefix)&&this._relatedInfo},this);break;default:return}if(J){b=y.clone(b);w=b.value;var h=b.title?this._processFieldsInLinks(this._fixTokens(b.title,
d),f):"",e=b.caption?this._processFieldsInLinks(this._fixTokens(b.caption,d),f):"";b.title=h?y.trim(a.substitute(g,h,H)||""):"";b.caption=e?y.trim(a.substitute(g,e,H)||""):"";if("image"===b.type)w.sourceURL=a.substitute(f,this._fixTokens(w.sourceURL,d)),w.linkURL&&(w.linkURL=y.trim(a.substitute(f,this._fixTokens(w.linkURL,d))||""));else{var l,q;z.forEach(w.fields,function(a,b){if(-1!==a.indexOf(this._relatedFieldPrefix))q=this._getRelatedChartInfos(a,w,f,H),q instanceof Array?w.fields=q:w.fields[b]=
q;else{var h=f[a],h=void 0===h?null:h;l=f[w.normalizeField]||0;h&&l&&(h/=l);w.fields[b]={y:h,tooltip:(this._fieldLabels[a.toLowerCase()]||a)+":\x3cbr/\x3e"+this._formatValue(h,a,H,!!l)}}},this)}F.push(b)}},this));return{title:n,description:q,hasDescription:!!e.description,fields:u&&u.length?u:null,mediaInfos:F&&F.length?F:null,formatted:g,editSummary:d&&d.getEditSummary?d.getEditSummary(b):""}},_getRelatedChartInfos:function(a,b,c,e){var d,f,g,k,q,u;d=[];u=this._fromRelatedFieldName(a);q=u[0];f=this._relatedInfo[q];
q=this._relatedLayersInfo[q];f&&z.forEach(f.relatedFeatures,function(q){q=q.attributes;var f,C;for(C in q)if(q.hasOwnProperty(C)&&C===u[1]){f={};k=q[C];b.normalizeField&&(g=-1!==b.normalizeField.indexOf(this._relatedFieldPrefix)?q[this._fromRelatedFieldName(b.normalizeField)[1]]:c[b.normalizeField]);k&&g&&(k/=g);if(b.tooltipField)if(-1!==b.tooltipField.indexOf(this._relatedFieldPrefix)){var n=this._fromRelatedFieldName(b.tooltipField)[1];f.tooltip=q[n]&&"string"===typeof q[n]?q[n]+":\x3cbr/\x3e"+
this._formatValue(k,q[n],e,!!g):n+":\x3cbr/\x3e"+this._formatValue(k,n,e,!!g)}else f.tooltip=(this._fieldLabels[a.toLowerCase()]||a)+":\x3cbr/\x3e"+this._formatValue(k,b.tooltipField,e,!!g);else f.tooltip=k;f.y=k;d.push(f)}},this);return"esriRelCardinalityOneToMany"===q.relation.cardinality||"esriRelCardinalityManyToMany"===q.relation.cardinality?d:d[0]},_dateFormats:{shortDate:"(datePattern: 'M/d/y', selector: 'date')",shortDateLE:"(datePattern: 'd/M/y', selector: 'date')",longMonthDayYear:"(datePattern: 'MMMM d, y', selector: 'date')",
dayShortMonthYear:"(datePattern: 'd MMM y', selector: 'date')",longDate:"(datePattern: 'EEEE, MMMM d, y', selector: 'date')",shortDateShortTime:"(datePattern: 'M/d/y', timePattern: 'h:mm a', selector: 'date and time')",shortDateLEShortTime:"(datePattern: 'd/M/y', timePattern: 'h:mm a', selector: 'date and time')",shortDateShortTime24:"(datePattern: 'M/d/y', timePattern: 'H:mm', selector: 'date and time')",shortDateLEShortTime24:"(datePattern: 'd/M/y', timePattern: 'H:mm', selector: 'date and time')",
shortDateLongTime:"(datePattern: 'M/d/y', timePattern: 'h:mm:ss a', selector: 'date and time')",shortDateLELongTime:"(datePattern: 'd/M/y', timePattern: 'h:mm:ss a', selector: 'date and time')",shortDateLongTime24:"(datePattern: 'M/d/y', timePattern: 'H:mm:ss', selector: 'date and time')",shortDateLELongTime24:"(datePattern: 'd/M/y', timePattern: 'H:mm:ss', selector: 'date and time')",longMonthYear:"(datePattern: 'MMMM y', selector: 'date')",shortMonthYear:"(datePattern: 'MMM y', selector: 'date')",
year:"(datePattern: 'y', selector: 'date')"},_reHref:/href\s*=\s*\"([^\"]+)\"/ig,_reHrefApos:/href\s*=\s*\'([^\']+)\'/ig,_fixTokens:function(a,b){var c=this;return a.replace(/(\{([^\{\r\n]+)\})/g,function(a,h,e){a=c._getLayerFieldInfo(b,e);return"$"+(a?"{"+a.name+"}":h)})},_encodeAttributes:function(a){a=y.clone(a)||{};var b,c;for(b in a)if((c=a[b])&&"string"===typeof c)c=encodeURIComponent(c).replace(/\'/g,"\x26apos;"),a[b]=c;return a},_processFieldsInLinks:function(a,b){var c=this._encodeAttributes(b),
e=this;a&&(a=a.replace(this._reHref,function(a,h){return e._addValuesToHref(a,h,b,c)}).replace(this._reHrefApos,function(a,h){return e._addValuesToHref(a,h,b,c)}));return a},_addValuesToHref:function(b,c,e,d){c=c&&y.trim(c);return a.substitute(c&&0===c.indexOf("${")?e:d,b)},_getLayerFieldInfo:function(a,b){return a&&a.getField?a.getField(b):null},_formatValue:function(b,c,e,d){var f=this._fieldsMap[c.toLowerCase()],g=f&&f.format;c=-1!==z.indexOf(e.dateFormat.properties,c);var n="number"===typeof b&&
!c&&(!g||!g.dateFormat);if(!a.isDefined(b)||!f||!a.isDefined(g))return n?this._forceLTR(b):b;var x="",f=[],q=g.hasOwnProperty("places")||g.hasOwnProperty("digitSeparator"),u=g.hasOwnProperty("digitSeparator")?g.digitSeparator:!0;if(q&&!c)x="NumberFormat",f.push("places: "+(a.isDefined(g.places)&&(!d||0<g.places)?Number(g.places):"Infinity")),f.length&&(x+="("+f.join(",")+")");else if(g.dateFormat)x="DateFormat"+this._insertOffset(this._dateFormats[g.dateFormat]||this._dateFormats.shortDateShortTime);
else return n?this._forceLTR(b):b;var v=this._applyFormatting(b,x,e);q&&-1<b.constructor.toString().indexOf("Array")&&(v="",z.forEach(b,y.hitch(this,function(a){v=v+this._applyFormatting(a,x,e)+" "})));q&&!u&&k.group&&(v=v.replace(RegExp("\\"+k.group,"g"),""));return n?this._forceLTR(v):v},_applyFormatting:function(b,c,e){return a.substitute({myKey:b},"${myKey:"+c+"}",e)||""},_forceLTR:function(a){var b=n("ie");return b&&10>=b?a:"\x3cspan class\x3d'esriNumericValue'\x3e"+a+"\x3c/span\x3e"},_insertOffset:function(b){b&&
(b=a.isDefined(this.utcOffset)?b.replace(/\)\s*$/,", utcOffset:"+this.utcOffset+")"):b);return b},_getDomainName:function(a,b,c,e,d,f){return(a=a.getDomain&&a.getDomain(d,{feature:b}))&&a.codedValues?a.getName(f):null},_getTypeName:function(a,b,c){return(a=a.getType&&a.getType(b))&&a.name},_getRelatedRecords:function(a){var b=a.graphic,c=new G,e;this._relatedLayersInfo?this._queryRelatedLayers(b).then(y.hitch(this,function(a){this._setRelatedRecords(b,a);c.resolve(a)}),y.hitch(this,this._handlerErrorResponse,
c)):this._getRelatedLayersInfo(a).then(y.hitch(this,function(a){for(e in a)a.hasOwnProperty(e)&&a[e]&&(this._relatedLayersInfo[e].relatedLayerInfo=a[e]);this._queryRelatedLayers(b).then(y.hitch(this,function(a){this._setRelatedRecords(b,a);c.resolve(a)}),y.hitch(this,this._handlerErrorResponse,c))}),y.hitch(this,this._handlerErrorResponse,c));return c.promise},_getRelatedLayersInfo:function(a){var c=a.fieldsInfo,e,f,k={};e=a.graphic.getLayer();this._relatedLayersInfo||(this._relatedLayersInfo={});
z.forEach(c,function(a){var b,c,d,f;b=this._fromRelatedFieldName(a.fieldName);c=b[0];b=b[1];c&&(this._relatedLayersInfo[c]||(z.some(e.relationships,function(a){if(a.id==c)return f=a,!0}),f&&(this._relatedLayersInfo[c]={relation:f,relatedFields:[],outStatistics:[]})),this._relatedLayersInfo[c]&&(this._relatedLayersInfo[c].relatedFields.push(b),a.statisticType&&(d=new g,d.statisticType=a.statisticType,d.onStatisticField=b,d.outStatisticFieldName=b,this._relatedLayersInfo[c].outStatistics.push(d))))},
this);for(f in this._relatedLayersInfo)this._relatedLayersInfo.hasOwnProperty(f)&&this._relatedLayersInfo[f]&&(a=this._relatedLayersInfo[f].relation,a=e.url.replace(/[0-9]+$/,a.relatedTableId),this._relatedLayersInfo[f].relatedLayerUrl=a,k[f]=d({url:a,content:{f:"json"},callbackParamName:"callback"}));return b(k)},_queryRelatedLayers:function(a){var c={},e;for(e in this._relatedLayersInfo)this._relatedLayersInfo.hasOwnProperty(e)&&(c[e]=this._queryRelatedLayer({graphic:a,relatedInfo:this._relatedLayersInfo[e]}));
return b(c)},_queryRelatedLayer:function(a){var e,d,g,k,n,s,x,q,u,v;e=a.graphic;d=e.getLayer().url.match(/[0-9]+$/g)[0];q=a.relatedInfo;x=q.relatedLayerInfo;u=q.relatedLayerUrl;v=q.relation;z.some(x.relationships,function(a){if(a.relatedTableId===parseInt(d,10))return g=a,!0},this);g&&(a=new c,z.some(x.fields,function(a){if(a.name===g.keyField)return n=-1!==z.indexOf(["esriFieldTypeSmallInteger","esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble"],a.type)?"number":"string",!0}),k="string"===
n?g.keyField+"\x3d'"+e.attributes[v.keyField]+"'":g.keyField+"\x3d"+e.attributes[v.keyField],a.where=k,a.outFields=q.relatedFields,q.outStatistics&&(0<q.outStatistics.length&&x.supportsStatistics)&&(s=new c,s.where=a.where,s.outFields=a.outFields,s.outStatistics=q.outStatistics),e=new f(u),k=[],k.push(e.execute(a)),s&&k.push(e.execute(s)));return b(k)},_setRelatedRecords:function(b,c){this._relatedInfo=[];for(var e in c)if(c.hasOwnProperty(e)&&c[e]){var d=c[e];this._relatedInfo[e]={};this._relatedInfo[e].relatedFeatures=
d[0].features;a.isDefined(d[1])&&(this._relatedInfo[e].relatedStatsFeatures=d[1].features)}},_handlerErrorResponse:function(a,b){a.reject(b)},_fromRelatedFieldName:function(a){var b=[];-1!==a.indexOf(this._relatedFieldPrefix)&&(a=a.split("/"),b=a.slice(1));return b},_toRelatedFieldName:function(a){var b="";a&&0<a.length&&(b=this._relatedFieldPrefix+a[0]+"/"+a[1]);return b}});E("extend-esri")&&(e.PopupInfo=e.PopupInfoTemplate=A);return A})},"*noref":1}});
define("esri/layers/LabelLayer","require dojo/_base/declare dojo/_base/lang dojo/number dojo/i18n!dojo/cldr/nls/number dojo/_base/array dojo/_base/connect dojo/has dojox/gfx/_base ../kernel ../lang ../graphic ../PopupInfo ./labelLayerUtils/DynamicLabelClass ./labelLayerUtils/StaticLabelClass ../symbols/TextSymbol ../symbols/ShieldLabelSymbol ../geometry/Extent ../geometry/Point ../geometry/webMercatorUtils ./GraphicsLayer ./LabelClass ../renderers/SimpleRenderer".split(" "),function(A,y,z,F,D,E,G,
n,b,a,e,d,c,f,g,k,h,l,p,m,r,t,s){function x(a){return"sizeInfo"===a.type}A=y(r,{declaredClass:"esri.layers.LabelLayer",constructor:function(a){this.id="labels";this.featureLayers=[];this._featureLayerInfos=[];this._preparedLabels=[];this._engineType="STATIC";this._mapEventHandlers=[];a&&(a.id&&(this.id=a.id),a.mode&&(this._engineType="DYNAMIC"===a.mode.toUpperCase()?"DYNAMIC":"STATIC"))},_setMap:function(a){var b=this.inherited(arguments);this._map&&this._mapEventHandlers.push(this._map.on("extent-change",
z.hitch(this,"refresh")));this.refresh();return b},_unsetMap:function(){var a;for(a=0;a<this._mapEventHandlers.length;a++)G.disconnect(this._mapEventHandlers[a]);this.refresh();this.inherited(arguments)},setAlgorithmType:function(a){this._engineType=a&&"DYNAMIC"===a.toUpperCase()?"DYNAMIC":"STATIC";this.refresh()},addFeatureLayer:function(a,b,c,e){if(!this.getFeatureLayer(a.layerId)){var d=[];d.push(a.on("update-end",z.hitch(this,"refresh")));d.push(a.on("suspend",z.hitch(this,"refresh")));d.push(a.on("resume",
z.hitch(this,"refresh")));d.push(a.on("edits-complete",z.hitch(this,"refresh")));d.push(a.on("labeling-info-change",z.hitch(this,"refresh")));d.push(a.on("time-extent-change",z.hitch(this,"refresh")));d.push(a.on("show-labels-change",z.hitch(this,"refresh")));this._featureLayerInfos.push({FeatureLayer:a,LabelExpressionInfo:c,LabelingOptions:e,LabelRenderer:b,EventHandlers:d});this.featureLayers.push(a);this.refresh()}},getFeatureLayer:function(a){var b,c;for(b=0;b<this.featureLayers.length;b++)if(c=
this.featureLayers[b],void 0!==c&&c.id==a)return c;return null},removeFeatureLayer:function(a){var b;a=this.getFeatureLayer(a);if(void 0!==a&&(b=E.indexOf(this.featureLayers,a),-1<b)){this.featureLayers.splice(b,1);for(a=0;a<this._featureLayerInfos[b].EventHandlers.length;a++)G.disconnect(this._featureLayerInfos[b].EventHandlers[a]);this._featureLayerInfos.splice(b,1);this.refresh()}},removeAllFeatureLayers:function(){var a;for(a=0;a<this.featureLayers.length;a++){for(var b=0;b<this._featureLayerInfos[a].EventHandlers.length;b++)G.disconnect(this._featureLayerInfos[a].EventHandlers[b]);
this.featureLayers=[];this._featureLayerInfos=[]}this.refresh()},getFeatureLayers:function(){return this.featureLayers},getFeatureLayerInfo:function(a){var b,c;for(b=0;b<this.featureLayers.length;b++)if(c=this.featureLayers[b],void 0!==c&&c.id==a)return this._featureLayerInfos[b];return null},refresh:function(a){var b,c,e,d,h,k=[],l,m="DYNAMIC"===this._engineType?new f:new g;if(this._map){m.setMap(this._map,this);this._preparedLabels=[];for(a=0;a<this.featureLayers.length;a++)if(c=this.featureLayers[a],
c.visible&&c.showLabels&&c.visibleAtMapScale&&!c._suspended)if(b=this._featureLayerInfos[a],h=this._convertOptions(null),b.LabelRenderer){if(k=c.labelingInfo)if(l=k[0])d=this._getLabelExpression(l),h=this._convertOptions(l);e=b.LabelRenderer;b.LabelExpressionInfo&&(d=b.LabelExpressionInfo);b.LabelingOptions&&(h=this._convertOptions(null),void 0!==b.LabelingOptions.pointPriorities&&(k=b.LabelingOptions.pointPriorities,h.pointPriorities="above-center"==k||"AboveCenter"==k||"esriServerPointLabelPlacementAboveCenter"==
k?"AboveCenter":"above-left"==k||"AboveLeft"==k||"esriServerPointLabelPlacementAboveLeft"==k?"AboveLeft":"above-right"==k||"AboveRight"==k||"esriServerPointLabelPlacementAboveRight"==k?"AboveRight":"below-center"==k||"BelowCenter"==k||"esriServerPointLabelPlacementBelowCenter"==k?"BelowCenter":"below-left"==k||"BelowLeft"==k||"esriServerPointLabelPlacementBelowLeft"==k?"BelowLeft":"below-right"==k||"BelowRight"==k||"esriServerPointLabelPlacementBelowRight"==k?"BelowRight":"center-center"==k||"CenterCenter"==
k||"esriServerPointLabelPlacementCenterCenter"==k?"CenterCenter":"center-left"==k||"CenterLeft"==k||"esriServerPointLabelPlacementCenterLeft"==k?"CenterLeft":"center-right"==k||"CenterRight"==k||"esriServerPointLabelPlacementCenterRight"==k?"CenterRight":"AboveRight"),void 0!==b.LabelingOptions.lineLabelPlacement&&(h.lineLabelPlacement=b.LabelingOptions.lineLabelPlacement),void 0!==b.LabelingOptions.lineLabelPosition&&(h.lineLabelPosition=b.LabelingOptions.lineLabelPosition),void 0!==b.LabelingOptions.labelRotation&&
(h.labelRotation=b.LabelingOptions.labelRotation),void 0!==b.LabelingOptions.howManyLabels&&(h.howManyLabels=b.LabelingOptions.howManyLabels));e instanceof t&&(d=this._getLabelExpression(e),e=new s(e.symbol),h=this._convertOptions(e));this._addLabels(c,e,d,h)}else if(k=c.labelingInfo)for(b=k.length-1;0<=b;b--)if(l=k[b])e=new t(l instanceof t?l.toJson():l),d=this._getLabelExpression(l),h=this._convertOptions(l),this._addLabels(c,e,d,h);d=m._process(this._preparedLabels);this.clear();this.drawLabels(this._map,
d)}},drawLabels:function(a,b){this._scale=(a.extent.xmax-a.extent.xmin)/a.width;var c;for(c=0;c<b.length;c++){var e=b[c],f=e.x,g=e.y,h=e.text,l=e.angle,m=e.layer.labelSymbol;"polyline"==e.layer.geometry.type&&e.layer.options.labelRotation&&m.setAngle(l*(180/Math.PI));m.setText(h);e=f;m instanceof k&&(f=m.getHeight(),l=Math.sin(l),e-=0.25*f*this._scale*l,g-=0.33*f*this._scale);l=new d(new p(e,g,a.extent.spatialReference));l.setSymbol(m);this.add(l)}},_addLabels:function(a,b,c,e){var d,f,g,h;if(this._isWithinScaleRange(b.minScale,
b.maxScale)&&c&&""!==c){var k=this._map,l=!a.url&&!k.spatialReference.equals(a.spatialReference);for(d=0;d<a.graphics.length;d++)if(f=a.graphics[d],!1!==f.visible){g=f.geometry;if(l){if(!m.canProject(g,k))continue;g=m.project(g,k)}g&&(this._isWhere(b.where,f.attributes)&&this._isWithinScreenArea(g))&&(h=this._buildLabelText(c,f.attributes,a.fields,e),this._addLabel(h,b,a.renderer,f,e,g,k))}}},_isWithinScreenArea:function(a){a="point"===a.type?new l(a.x,a.y,a.x,a.y,a.spatialReference):a.getExtent();
if(void 0===a)return!1;a=this._intersects(this._map,a);return null===a||0===a.length?!1:!0},_isWithinScaleRange:function(a,b){var c=this._map.getScale();return 0<a&&c>=a||0<b&&c<=b?!1:!0},_isWhere:function(a,b){try{if(!a)return!0;if(a){var c=a.split(" ");if(3===c.length)return this._sqlEquation(b[c[0].substr(1,c[0].length-2)],c[1],c[2]);if(7===c.length){var e=this._sqlEquation(b[c[0].substr(1,c[0].length-2)],c[1],c[2]),d=c[3],f=this._sqlEquation(b[c[4].substr(1,c[4].length-2)],c[5],c[6]);switch(d){case "AND":return e&&
f;case "OR":return e||f}}}return!1}catch(g){console.log("Error.: can't parse \x3d "+a)}},_sqlEquation:function(a,b,c){switch(b){case "\x3d":return a==c?!0:!1;case "\x3c\x3e":return a!=c?!0:!1;case "\x3e":return a>c?!0:!1;case "\x3e\x3d":return a>=c?!0:!1;case "\x3c":return a<c?!0:!1;case "\x3c\x3d":return a<=c?!0:!1}return!1},_getSizeInfo:function(a){return a?a.sizeInfo||E.filter(a.visualVariables,x)[0]:null},_addLabel:function(a,c,e,d,f,g,l){var m,n,p,r;if(a&&""!==z.trim(a)&&c){a=a.replace(/\s+/g,
" ");m=c.getSymbol(d);m instanceof k?(m=new k(m.toJson()),m.setVerticalAlignment("baseline"),m.setHorizontalAlignment("center")):m=m instanceof h?new h(m.toJson()):new k;m.setText(a);c.symbol=m;if(p=this._getProportionalSize(c.sizeInfo,d.attributes))m instanceof k?m.setSize(p):m instanceof h&&(m.setWidth(p),m.setHeight(p));r=p=0;if(e){n=e.getSymbol(d);var s=this._getSizeInfo(e),t;s&&(t=e.getSize(d,{sizeInfo:s,resolution:l.getResolutionInMeters()}));if(null!=t)p=r=t;else if(n)if("simplemarkersymbol"==
n.type)r=p=n.size;else if("picturemarkersymbol"==n.type)p=n.width,r=n.height;else if("simplelinesymbol"==n.type||"cartographiclinesymbol"==n.type)p=n.width}e={};e.graphic=d;e.options=f;e.geometry=g;e.labelRenderer=c;e.labelSymbol=m;e.labelWidth=m.getWidth()/2;e.labelHeight=m.getHeight()/2;e.symbolWidth=b.normalizedLength(p)/2;e.symbolHeight=b.normalizedLength(r)/2;e.text=a;e.angle=m.angle;this._preparedLabels.push(e)}},_buildLabelText:function(a,b,d,f){return a.replace(/{[^}]*}/g,function(a){var g,
h=a;for(g=0;g<d.length;g++)if("{"+d[g].name+"}"==a){var h=b[d[g].name],k=d[g].domain;if(k&&z.isObject(k)){if("codedValue"==k.type)for(a=0;a<k.codedValues.length;a++)k.codedValues[a].code==h&&(h=k.codedValues[a].name);else"range"==k.type&&(k.minValue<=h&&h<=k.maxValue)&&(h=k.name);break}k=d[g].type;if(f.fieldInfos){var l=f.fieldInfos;for(g=0;g<l.length;g++)if("{"+l[g].fieldName+"}"==a){a=l[g].format;if("esriFieldTypeDate"==k)(a="DateFormat"+c.prototype._dateFormats[a.dateFormat?a.dateFormat:"shortDate"])&&
(h=e.substitute({myKey:h},"${myKey:"+a+"}"));else if(("esriFieldTypeInteger"==k||"esriFieldTypeSingle"==k||"esriFieldTypeSmallInteger"==k||"esriFieldTypeLong"==k||"esriFieldTypeDouble"==k)&&a)h=F.format(h,{places:a.places}),a.digitSeparator||D.group&&(h=h.replace(RegExp("\\"+D.group,"g"),""));break}}break}else h="";return null===h?"":h})},_getLabelExpression:function(a){return a.labelExpressionInfo?a.labelExpressionInfo.value:this._validSyntax(a.labelExpression)?this._convertLabelExpression(a.labelExpression):
""},_validSyntax:function(a){return/^(\s*\[[^\]]+\]\s*)+$/i.test(a)},_convertLabelExpression:function(a){return a.replace(RegExp("\\[","g"),"{").replace(RegExp("\\]","g"),"}")},_getProportionalSize:function(a,b){if(!a)return null;var c=e.substitute(b,"${"+a.field+"}",{first:!0});return!a.minSize||!a.maxSize||!a.minDataValue||!a.maxDataValue||!c||0>=a.maxDataValue-a.minDataValue?null:(a.maxSize-a.minSize)/(a.maxDataValue-a.minDataValue)*(c-a.minDataValue)+a.minSize},_convertOptions:function(a){var b=
"shortDate",c=null,e=null,d="",f=!0;a&&(a.format&&(b=a.format.dateFormat,c={places:a.format.places,digitSeparator:a.format.digitSeparator}),e=a.fieldInfos,d=a.labelPlacement);if("always-horizontal"==d||"esriServerPolygonPlacementAlwaysHorizontal"==d)f=!1;return{dateFormat:b,numberFormat:c,fieldInfos:e,pointPriorities:"above-center"==d||"esriServerPointLabelPlacementAboveCenter"==d?"AboveCenter":"above-left"==d||"esriServerPointLabelPlacementAboveLeft"==d?"AboveLeft":"above-right"==d||"esriServerPointLabelPlacementAboveRight"==
d?"AboveRight":"below-center"==d||"esriServerPointLabelPlacementBelowCenter"==d?"BelowCenter":"below-left"==d||"esriServerPointLabelPlacementBelowLeft"==d?"BelowLeft":"below-right"==d||"esriServerPointLabelPlacementBelowRight"==d?"BelowRight":"center-center"==d||"esriServerPointLabelPlacementCenterCenter"==d?"CenterCenter":"center-left"==d||"esriServerPointLabelPlacementCenterLeft"==d?"CenterLeft":"center-right"==d||"esriServerPointLabelPlacementCenterRight"==d?"CenterRight":"AboveRight",lineLabelPlacement:"above-start"==
d||"below-start"==d||"center-start"==d?"PlaceAtStart":"above-end"==d||"below-end"==d||"center-end"==d?"PlaceAtEnd":"PlaceAtCenter",lineLabelPosition:"above-after"==d||"esriServerLinePlacementAboveAfter"==d||"above-along"==d||"esriServerLinePlacementAboveAlong"==d||"above-before"==d||"esriServerLinePlacementAboveBefore"==d||"above-start"==d||"esriServerLinePlacementAboveStart"==d||"above-end"==d||"esriServerLinePlacementAboveEnd"==d?"Above":"below-after"==d||"esriServerLinePlacementBelowAfter"==d||
"below-along"==d||"esriServerLinePlacementBelowAlong"==d||"below-before"==d||"esriServerLinePlacementBelowBefore"==d||"below-start"==d||"esriServerLinePlacementBelowStart"==d||"below-end"==d||"esriServerLinePlacementBelowEnd"==d?"Below":"center-after"==d||"esriServerLinePlacementCenterAfter"==d||"center-along"==d||"esriServerLinePlacementCenterAlong"==d||"center-before"==d||"esriServerLinePlacementCenterBefore"==d||"center-start"==d||"esriServerLinePlacementCenterStart"==d||"center-end"==d||"esriServerLinePlacementCenterEnd"==
d?"OnLine":"Above",labelRotation:f,howManyLabels:"OneLabel"}}});n("extend-esri")&&z.setObject("layers.LabelLayer",A,a);return A});