// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.16/esri/copyright.txt for details.
//>>built
require({cache:{"dijit/a11yclick":function(){define(["dojo/keys","dojo/mouse","dojo/on","dojo/touch"],function(h,n,f,r){function q(b){if((b.keyCode===h.ENTER||b.keyCode===h.SPACE)&&!/input|button|textarea/i.test(b.target.nodeName))for(b=b.target;b;b=b.parentNode)if(b.dojoClick)return!0}var d;f(document,"keydown",function(b){q(b)?(d=b.target,b.preventDefault()):d=null});f(document,"keyup",function(b){q(b)&&b.target==d&&(d=null,f.emit(b.target,"click",{cancelable:!0,bubbles:!0,ctrlKey:b.ctrlKey,shiftKey:b.shiftKey,
metaKey:b.metaKey,altKey:b.altKey,_origType:b.type}))});var k=function(b,d){b.dojoClick=!0;return f(b,"click",d)};k.click=k;k.press=function(b,d){var a=f(b,r.press,function(a){("mousedown"!=a.type||n.isLeft(a))&&d(a)}),t=f(b,"keydown",function(a){(a.keyCode===h.ENTER||a.keyCode===h.SPACE)&&d(a)});return{remove:function(){a.remove();t.remove()}}};k.release=function(b,d){var a=f(b,r.release,function(a){("mouseup"!=a.type||n.isLeft(a))&&d(a)}),t=f(b,"keyup",function(a){(a.keyCode===h.ENTER||a.keyCode===
h.SPACE)&&d(a)});return{remove:function(){a.remove();t.remove()}}};k.move=r.move;return k})},"dijit/Destroyable":function(){define(["dojo/_base/array","dojo/aspect","dojo/_base/declare"],function(h,n,f){return f("dijit.Destroyable",null,{destroy:function(f){this._destroyed=!0},own:function(){var f=["destroyRecursive","destroy","remove"];h.forEach(arguments,function(q){function d(){b.remove();h.forEach(s,function(a){a.remove()})}var k,b=n.before(this,"destroy",function(a){q[k](a)}),s=[];q.then?(k=
"cancel",q.then(d,d)):h.forEach(f,function(a){"function"===typeof q[a]&&(k||(k=a),s.push(n.after(q,a,d,!0)))})},this);return arguments}})})},"dijit/_TemplatedMixin":function(){define("dojo/cache dojo/_base/declare dojo/dom-construct dojo/_base/lang dojo/on dojo/sniff dojo/string ./_AttachMixin".split(" "),function(h,n,f,r,q,d,k,b){var s=n("dijit._TemplatedMixin",b,{templateString:null,templatePath:null,_skipNodeCache:!1,searchContainerNode:!0,_stringRepl:function(a){var b=this.declaredClass,d=this;
return k.substitute(a,this,function(a,f){"!"==f.charAt(0)&&(a=r.getObject(f.substr(1),!1,d));if("undefined"==typeof a)throw Error(b+" template:"+f);return null==a?"":"!"==f.charAt(0)?a:this._escapeValue(""+a)},this)},_escapeValue:function(a){return a.replace(/["'<>&]/g,function(a){return{"\x26":"\x26amp;","\x3c":"\x26lt;","\x3e":"\x26gt;",'"':"\x26quot;","'":"\x26#x27;"}[a]})},buildRendering:function(){if(!this._rendered){this.templateString||(this.templateString=h(this.templatePath,{sanitize:!0}));
var a=s.getCachedTemplate(this.templateString,this._skipNodeCache,this.ownerDocument),b;if(r.isString(a)){if(b=f.toDom(this._stringRepl(a),this.ownerDocument),1!=b.nodeType)throw Error("Invalid template: "+a);}else b=a.cloneNode(!0);this.domNode=b}this.inherited(arguments);this._rendered||this._fillContent(this.srcNodeRef);this._rendered=!0},_fillContent:function(a){var b=this.containerNode;if(a&&b)for(;a.hasChildNodes();)b.appendChild(a.firstChild)}});s._templateCache={};s.getCachedTemplate=function(a,
b,d){var u=s._templateCache,h=a,p=u[h];if(p){try{if(!p.ownerDocument||p.ownerDocument==(d||document))return p}catch(n){}f.destroy(p)}a=k.trim(a);if(b||a.match(/\$\{([^\}]+)\}/g))return u[h]=a;b=f.toDom(a,d);if(1!=b.nodeType)throw Error("Invalid template: "+a);return u[h]=b};d("ie")&&q(window,"unload",function(){var a=s._templateCache,b;for(b in a){var d=a[b];"object"==typeof d&&f.destroy(d);delete a[b]}});return s})},"dojo/cache":function(){define(["./_base/kernel","./text"],function(h){return h.cache})},
"dijit/_AttachMixin":function(){define("require dojo/_base/array dojo/_base/connect dojo/_base/declare dojo/_base/lang dojo/mouse dojo/on dojo/touch ./_WidgetBase".split(" "),function(h,n,f,r,q,d,k,b,s){var a=q.delegate(b,{mouseenter:d.enter,mouseleave:d.leave,keypress:f._keypress}),t;f=r("dijit._AttachMixin",null,{constructor:function(){this._attachPoints=[];this._attachEvents=[]},buildRendering:function(){this.inherited(arguments);this._attachTemplateNodes(this.domNode);this._beforeFillContent()},
_beforeFillContent:function(){},_attachTemplateNodes:function(a){for(var b=a;;)if(1==b.nodeType&&(this._processTemplateNode(b,function(a,b){return a.getAttribute(b)},this._attach)||this.searchContainerNode)&&b.firstChild)b=b.firstChild;else{if(b==a)break;for(;!b.nextSibling;)if(b=b.parentNode,b==a)return;b=b.nextSibling}},_processTemplateNode:function(a,b,d){var f=!0,h=this.attachScope||this,l=b(a,"dojoAttachPoint")||b(a,"data-dojo-attach-point");if(l)for(var k=l.split(/\s*,\s*/);l=k.shift();)q.isArray(h[l])?
h[l].push(a):h[l]=a,f="containerNode"!=l,this._attachPoints.push(l);if(b=b(a,"dojoAttachEvent")||b(a,"data-dojo-attach-event")){l=b.split(/\s*,\s*/);for(k=q.trim;b=l.shift();)if(b){var g=null;-1!=b.indexOf(":")?(g=b.split(":"),b=k(g[0]),g=k(g[1])):b=k(b);g||(g=b);this._attachEvents.push(d(a,b,q.hitch(h,g)))}}return f},_attach:function(b,d,f){d=d.replace(/^on/,"").toLowerCase();d="dijitclick"==d?t||(t=h("./a11yclick")):a[d]||d;return k(b,d,f)},_detachTemplateNodes:function(){var a=this.attachScope||
this;n.forEach(this._attachPoints,function(b){delete a[b]});this._attachPoints=[];n.forEach(this._attachEvents,function(a){a.remove()});this._attachEvents=[]},destroyRendering:function(){this._detachTemplateNodes();this.inherited(arguments)}});q.extend(s,{dojoAttachEvent:"",dojoAttachPoint:""});return f})},"dijit/_WidgetBase":function(){define("require dojo/_base/array dojo/aspect dojo/_base/config dojo/_base/connect dojo/_base/declare dojo/dom dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/has dojo/_base/kernel dojo/_base/lang dojo/on dojo/ready dojo/Stateful dojo/topic dojo/_base/window ./Destroyable dojo/has!dojo-bidi?./_BidiMixin ./registry".split(" "),
function(h,n,f,r,q,d,k,b,s,a,t,A,u,x,p,v,l,F,g,y,B,G,w){function C(a){return function(m){b[m?"set":"remove"](this.domNode,a,m);this._set(a,m)}}u.add("dijit-legacy-requires",!x.isAsync);u.add("dojo-bidi",!1);u("dijit-legacy-requires")&&l(0,function(){h(["dijit/_base/manager"])});var D={};r=d("dijit._WidgetBase",[F,B],{id:"",_setIdAttr:"domNode",lang:"",_setLangAttr:C("lang"),dir:"",_setDirAttr:C("dir"),"class":"",_setClassAttr:{node:"domNode",type:"class"},_setTypeAttr:null,style:"",title:"",tooltip:"",
baseClass:"",srcNodeRef:null,domNode:null,containerNode:null,ownerDocument:null,_setOwnerDocumentAttr:function(a){this._set("ownerDocument",a)},attributeMap:{},_blankGif:r.blankGif||h.toUrl("dojo/resources/blank.gif"),_introspect:function(){var a=this.constructor;if(!a._setterAttrs){var b=a.prototype,c=a._setterAttrs=[],a=a._onMap={},e;for(e in b.attributeMap)c.push(e);for(e in b)/^on/.test(e)&&(a[e.substring(2).toLowerCase()]=e),/^_set[A-Z](.*)Attr$/.test(e)&&(e=e.charAt(4).toLowerCase()+e.substr(5,
e.length-9),(!b.attributeMap||!(e in b.attributeMap))&&c.push(e))}},postscript:function(a,b){this.create(a,b)},create:function(a,b){this._introspect();this.srcNodeRef=k.byId(b);this._connects=[];this._supportingWidgets=[];this.srcNodeRef&&"string"==typeof this.srcNodeRef.id&&(this.id=this.srcNodeRef.id);a&&(this.params=a,p.mixin(this,a));this.postMixInProperties();this.id||(this.id=w.getUniqueId(this.declaredClass.replace(/\./g,"_")),this.params&&delete this.params.id);this.ownerDocument=this.ownerDocument||
(this.srcNodeRef?this.srcNodeRef.ownerDocument:document);this.ownerDocumentBody=y.body(this.ownerDocument);w.add(this);this.buildRendering();var c;if(this.domNode){this._applyAttributes();var e=this.srcNodeRef;e&&(e.parentNode&&this.domNode!==e)&&(e.parentNode.replaceChild(this.domNode,e),c=!0);this.domNode.setAttribute("widgetId",this.id)}this.postCreate();c&&delete this.srcNodeRef;this._created=!0},_applyAttributes:function(){var a={},b;for(b in this.params||{})a[b]=this._get(b);n.forEach(this.constructor._setterAttrs,
function(b){if(!(b in a)){var m=this._get(b);m&&this.set(b,m)}},this);for(b in a)this.set(b,a[b])},postMixInProperties:function(){},buildRendering:function(){this.domNode||(this.domNode=this.srcNodeRef||this.ownerDocument.createElement("div"));if(this.baseClass){var a=this.baseClass.split(" ");this.isLeftToRight()||(a=a.concat(n.map(a,function(a){return a+"Rtl"})));s.add(this.domNode,a)}},postCreate:function(){},startup:function(){this._started||(this._started=!0,n.forEach(this.getChildren(),function(a){!a._started&&
(!a._destroyed&&p.isFunction(a.startup))&&(a.startup(),a._started=!0)}))},destroyRecursive:function(a){this._beingDestroyed=!0;this.destroyDescendants(a);this.destroy(a)},destroy:function(a){function b(m){m.destroyRecursive?m.destroyRecursive(a):m.destroy&&m.destroy(a)}this._beingDestroyed=!0;this.uninitialize();n.forEach(this._connects,p.hitch(this,"disconnect"));n.forEach(this._supportingWidgets,b);this.domNode&&n.forEach(w.findWidgets(this.domNode,this.containerNode),b);this.destroyRendering(a);
w.remove(this.id);this._destroyed=!0},destroyRendering:function(z){this.bgIframe&&(this.bgIframe.destroy(z),delete this.bgIframe);this.domNode&&(z?b.remove(this.domNode,"widgetId"):a.destroy(this.domNode),delete this.domNode);this.srcNodeRef&&(z||a.destroy(this.srcNodeRef),delete this.srcNodeRef)},destroyDescendants:function(a){n.forEach(this.getChildren(),function(b){b.destroyRecursive&&b.destroyRecursive(a)})},uninitialize:function(){return!1},_setStyleAttr:function(a){var b=this.domNode;p.isObject(a)?
A.set(b,a):b.style.cssText=b.style.cssText?b.style.cssText+("; "+a):a;this._set("style",a)},_attrToDom:function(a,m,c){c=3<=arguments.length?c:this.attributeMap[a];n.forEach(p.isArray(c)?c:[c],function(e){var c=this[e.node||e||"domNode"];switch(e.type||"attribute"){case "attribute":p.isFunction(m)&&(m=p.hitch(this,m));e=e.attribute?e.attribute:/^on[A-Z][a-zA-Z]*$/.test(a)?a.toLowerCase():a;c.tagName?b.set(c,e,m):c.set(e,m);break;case "innerText":c.innerHTML="";c.appendChild(this.ownerDocument.createTextNode(m));
break;case "innerHTML":c.innerHTML=m;break;case "class":s.replace(c,m,this[a])}},this)},get:function(a){var b=this._getAttrNames(a);return this[b.g]?this[b.g]():this._get(a)},set:function(a,b){if("object"===typeof a){for(var c in a)this.set(c,a[c]);return this}c=this._getAttrNames(a);var e=this[c.s];if(p.isFunction(e))var d=e.apply(this,Array.prototype.slice.call(arguments,1));else{var e=this.focusNode&&!p.isFunction(this.focusNode)?"focusNode":"domNode",g=this[e]&&this[e].tagName,l;if(l=g)if(!(l=
D[g])){l=this[e];var f={},E;for(E in l)f[E.toLowerCase()]=!0;l=D[g]=f}E=l;c=a in this.attributeMap?this.attributeMap[a]:c.s in this?this[c.s]:E&&c.l in E&&"function"!=typeof b||/^aria-|^data-|^role$/.test(a)?e:null;null!=c&&this._attrToDom(a,b,c);this._set(a,b)}return d||this},_attrPairNames:{},_getAttrNames:function(a){var b=this._attrPairNames;if(b[a])return b[a];var c=a.replace(/^[a-z]|-[a-zA-Z]/g,function(a){return a.charAt(a.length-1).toUpperCase()});return b[a]={n:a+"Node",s:"_set"+c+"Attr",
g:"_get"+c+"Attr",l:c.toLowerCase()}},_set:function(a,b){var c=this[a];this[a]=b;if(this._created&&!(c===b||c!==c&&b!==b))this._watchCallbacks&&this._watchCallbacks(a,c,b),this.emit("attrmodified-"+a,{detail:{prevValue:c,newValue:b}})},_get:function(a){return this[a]},emit:function(a,b,c){b=b||{};void 0===b.bubbles&&(b.bubbles=!0);void 0===b.cancelable&&(b.cancelable=!0);b.detail||(b.detail={});b.detail.widget=this;var e,d=this["on"+a];d&&(e=d.apply(this,c?c:[b]));this._started&&!this._beingDestroyed&&
v.emit(this.domNode,a.toLowerCase(),b);return e},on:function(a,b){var c=this._onMap(a);return c?f.after(this,c,b,!0):this.own(v(this.domNode,a,b))[0]},_onMap:function(a){var b=this.constructor,c=b._onMap;if(!c){var c=b._onMap={},e;for(e in b.prototype)/^on/.test(e)&&(c[e.replace(/^on/,"").toLowerCase()]=e)}return c["string"==typeof a&&a.toLowerCase()]},toString:function(){return"[Widget "+this.declaredClass+", "+(this.id||"NO ID")+"]"},getChildren:function(){return this.containerNode?w.findWidgets(this.containerNode):
[]},getParent:function(){return w.getEnclosingWidget(this.domNode.parentNode)},connect:function(a,b,c){return this.own(q.connect(a,b,this,c))[0]},disconnect:function(a){a.remove()},subscribe:function(a,b){return this.own(g.subscribe(a,p.hitch(this,b)))[0]},unsubscribe:function(a){a.remove()},isLeftToRight:function(){return this.dir?"ltr"==this.dir.toLowerCase():t.isBodyLtr(this.ownerDocument)},isFocusable:function(){return this.focus&&"none"!=A.get(this.domNode,"display")},placeAt:function(b,d){var c=
!b.tagName&&w.byId(b);c&&c.addChild&&(!d||"number"===typeof d)?c.addChild(this,d):(c=c&&"domNode"in c?c.containerNode&&!/after|before|replace/.test(d||"")?c.containerNode:c.domNode:k.byId(b,this.ownerDocument),a.place(this.domNode,c,d),!this._started&&(this.getParent()||{})._started&&this.startup());return this},defer:function(a,b){var c=setTimeout(p.hitch(this,function(){c&&(c=null,this._destroyed||p.hitch(this,a)())}),b||0);return{remove:function(){c&&(clearTimeout(c),c=null);return null}}}});u("dojo-bidi")&&
r.extend(G);return r})},"dojo/touch":function(){define("./_base/kernel ./aspect ./dom ./dom-class ./_base/lang ./on ./has ./mouse ./domReady ./_base/window".split(" "),function(h,n,f,r,q,d,k,b,s,a){function t(a,b,c){return p&&c?function(a,b){return d(a,c,b)}:l?function(c,g){var l=d(c,b,function(a){g.call(this,a);m=(new Date).getTime()}),f=d(c,a,function(a){(!m||(new Date).getTime()>m+1E3)&&g.call(this,a)});return{remove:function(){l.remove();f.remove()}}}:function(b,c){return d(b,a,c)}}function A(a){do if(void 0!==
a.dojoClick)return a;while(a=a.parentNode)}function u(b,c,l){var h=A(b.target);if(g=!b.target.disabled&&h&&h.dojoClick)if(B=(y="useTarget"==g)?h:b.target,y&&b.preventDefault(),G=b.changedTouches?b.changedTouches[0].pageX-a.global.pageXOffset:b.clientX,w=b.changedTouches?b.changedTouches[0].pageY-a.global.pageYOffset:b.clientY,C=("object"==typeof g?g.x:"number"==typeof g?g:0)||4,D=("object"==typeof g?g.y:"number"==typeof g?g:0)||4,!F){F=!0;var k=function(b){g=y?f.isDescendant(a.doc.elementFromPoint(b.changedTouches?
b.changedTouches[0].pageX-a.global.pageXOffset:b.clientX,b.changedTouches?b.changedTouches[0].pageY-a.global.pageYOffset:b.clientY),B):g&&(b.changedTouches?b.changedTouches[0].target:b.target)==B&&Math.abs((b.changedTouches?b.changedTouches[0].pageX-a.global.pageXOffset:b.clientX)-G)<=C&&Math.abs((b.changedTouches?b.changedTouches[0].pageY-a.global.pageYOffset:b.clientY)-w)<=D};a.doc.addEventListener(c,function(a){k(a);y&&a.preventDefault()},!0);a.doc.addEventListener(l,function(a){k(a);if(g){z=(new Date).getTime();
var b=y?B:a.target;"LABEL"===b.tagName&&(b=f.byId(b.getAttribute("for"))||b);var c=a.changedTouches?a.changedTouches[0]:a,e=document.createEvent("MouseEvents");e._dojo_click=!0;e.initMouseEvent("click",!0,!0,a.view,a.detail,c.screenX,c.screenY,c.clientX,c.clientY,a.ctrlKey,a.altKey,a.shiftKey,a.metaKey,0,null);setTimeout(function(){d.emit(b,"click",e);z=(new Date).getTime()},0)}},!0);b=function(b){a.doc.addEventListener(b,function(a){!a._dojo_click&&((new Date).getTime()<=z+1E3&&!("INPUT"==a.target.tagName&&
r.contains(a.target,"dijitOffScreen")))&&(a.stopPropagation(),a.stopImmediatePropagation&&a.stopImmediatePropagation(),"click"==b&&(("INPUT"!=a.target.tagName||"radio"==a.target.type||"checkbox"==a.target.type)&&"TEXTAREA"!=a.target.tagName&&"AUDIO"!=a.target.tagName&&"VIDEO"!=a.target.tagName)&&a.preventDefault())},!0)};b("click");b("mousedown");b("mouseup")}}var x=5>k("ios"),p=k("pointer-events")||k("MSPointer"),v=function(){var a={},b;for(b in{down:1,move:1,up:1,cancel:1,over:1,out:1})a[b]=k("MSPointer")?
"MSPointer"+b.charAt(0).toUpperCase()+b.slice(1):"pointer"+b;return a}(),l=k("touch-events"),F,g,y=!1,B,G,w,C,D,z,m,c;p?s(function(){a.doc.addEventListener(v.down,function(a){u(a,v.move,v.up)},!0)}):l&&s(function(){function b(a){var c=q.delegate(a,{bubbles:!0});6<=k("ios")&&(c.touches=a.touches,c.altKey=a.altKey,c.changedTouches=a.changedTouches,c.ctrlKey=a.ctrlKey,c.metaKey=a.metaKey,c.shiftKey=a.shiftKey,c.targetTouches=a.targetTouches);return c}c=a.body();a.doc.addEventListener("touchstart",function(a){m=
(new Date).getTime();var b=c;c=a.target;d.emit(b,"dojotouchout",{relatedTarget:c,bubbles:!0});d.emit(c,"dojotouchover",{relatedTarget:b,bubbles:!0});u(a,"touchmove","touchend")},!0);d(a.doc,"touchmove",function(l){m=(new Date).getTime();var g=a.doc.elementFromPoint(l.pageX-(x?0:a.global.pageXOffset),l.pageY-(x?0:a.global.pageYOffset));g&&(c!==g&&(d.emit(c,"dojotouchout",{relatedTarget:g,bubbles:!0}),d.emit(g,"dojotouchover",{relatedTarget:c,bubbles:!0}),c=g),d.emit(g,"dojotouchmove",b(l))||l.preventDefault())});
d(a.doc,"touchend",function(c){m=(new Date).getTime();var g=a.doc.elementFromPoint(c.pageX-(x?0:a.global.pageXOffset),c.pageY-(x?0:a.global.pageYOffset))||a.body();d.emit(g,"dojotouchend",b(c))})});n={press:t("mousedown","touchstart",v.down),move:t("mousemove","dojotouchmove",v.move),release:t("mouseup","dojotouchend",v.up),cancel:t(b.leave,"touchcancel",p?v.cancel:null),over:t("mouseover","dojotouchover",v.over),out:t("mouseout","dojotouchout",v.out),enter:b._eventHandler(t("mouseover","dojotouchover",
v.over)),leave:b._eventHandler(t("mouseout","dojotouchout",v.out))};return h.touch=n})},"url:esri/dijit/templates/BasemapToggle.html":'\x3cdiv class\x3d"${theme}" role\x3d"presentation" style\x3d"display:none;"\x3e\r\n    \x3cdiv class\x3d"${_css.container}"\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"_toggleNode" title\x3d"${_i18n.widgets.basemapToggle.toggle}" role\x3d"button" class\x3d"${_css.toggleButton}" tabindex\x3d"0"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e',"*noref":1}});
define("esri/dijit/BasemapToggle","require dojo/Evented dojo/_base/declare dojo/_base/lang dojo/has ../kernel dijit/_WidgetBase dijit/a11yclick dijit/_TemplatedMixin dojo/on dojo/text!./templates/BasemapToggle.html dojo/i18n!../nls/jsapi dojo/dom-class dojo/dom-style dojo/dom-construct ../basemaps".split(" "),function(h,n,f,r,q,d,k,b,s,a,t,A,u,x,p,v){h=f("esri.dijit.BasemapToggle",[k,s,n],{templateString:t,options:{theme:"BasemapToggle",map:null,visible:!0,basemap:"hybrid",defaultBasemap:"streets",
basemaps:v},constructor:function(a,b){var d=r.mixin({},this.options,a);this.domNode=b;this._i18n=A;this.set("map",d.map);this.set("theme",d.theme);this.set("visible",d.visible);this.set("basemaps",d.basemaps);this.set("basemap",d.basemap);this.set("defaultBasemap",d.defaultBasemap);this.watch("theme",this._updateThemeWatch);this.watch("visible",this._visible);this._css={container:"basemapContainer",toggleButton:"toggleButton",basemapImage:"basemapImage",basemapImageContainer:"basemapImageContainer",
basemapImageBG:"basemapBG",basemapTitle:"basemapTitle"}},postCreate:function(){this.inherited(arguments);this.own(a(this._toggleNode,b,r.hitch(this,this.toggle)))},startup:function(){this.inherited(arguments);this.map||(this.destroy(),console.log("BasemapToggle::map required"));if(this.map.loaded)this._init();else a.once(this.map,"load",r.hitch(this,function(){this._init()}))},destroy:function(){this.inherited(arguments)},show:function(){this.set("visible",!0)},hide:function(){this.set("visible",
!1)},toggle:function(){var a=this.map.getBasemap();a&&this.set("defaultBasemap",a);var a=this.get("defaultBasemap"),b=this.get("basemap"),d={previousBasemap:a,currentBasemap:b};a!==b?(this.map.setBasemap(b),this.set("basemap",a),this._basemapChange()):d.error=Error("BasemapToggle::Current basemap is same as new basemap");this.emit("toggle",d)},_init:function(){this._visible();this._basemapChange();this.own(a(this.map,"basemap-change",r.hitch(this,function(){this._basemapChange()})));this.set("loaded",
!0);this.emit("load",{})},_getBasemapInfo:function(a){var b=this.get("basemaps");if(b&&b.hasOwnProperty(a))return b[a]},_updateImage:function(){var a=this.get("basemap"),a=this._getBasemapInfo(a),b=a.thumbnailUrl,d;d=""+('\x3cdiv class\x3d"'+this._css.basemapImageContainer+'"\x3e');d+='\x3cdiv class\x3d"'+this._css.basemapImage+'"\x3e\x3cdiv class\x3d"'+this._css.basemapImageBG+'" style\x3d"background-image:url('+b+')" title\x3d"'+a.title+'"\x3e\x3c/div\x3e\x3c/div\x3e';d+='\x3cdiv title\x3d"'+a.title+
'" class\x3d"'+this._css.basemapTitle+'"\x3e'+a.title+"\x3c/div\x3e";d+="\x3cdiv\x3e";p.empty(this._toggleNode);p.place(d,this._toggleNode,"only")},_basemapChange:function(){var a=this.map.getBasemap();a&&this.set("defaultBasemap",a);var a=this.get("defaultBasemap"),b=this.get("basemap");this._updateImage();u.remove(this._toggleNode,a);u.add(this._toggleNode,b)},_updateThemeWatch:function(a,b,d){this.get("loaded")&&(u.remove(this.domNode,b),u.add(this.domNode,d))},_visible:function(){this.get("visible")?
x.set(this.domNode,"display","block"):x.set(this.domNode,"display","none")}});q("extend-esri")&&r.setObject("dijit.BasemapToggle",h,d);return h});