// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.16/esri/copyright.txt for details.
//>>built
require({cache:{"dijit/a11yclick":function(){define(["dojo/keys","dojo/mouse","dojo/on","dojo/touch"],function(e,k,f,r){function m(b){if((b.keyCode===e.ENTER||b.keyCode===e.SPACE)&&!/input|button|textarea/i.test(b.target.nodeName))for(b=b.target;b;b=b.parentNode)if(b.dojoClick)return!0}var d;f(document,"keydown",function(b){m(b)?(d=b.target,b.preventDefault()):d=null});f(document,"keyup",function(b){m(b)&&b.target==d&&(d=null,f.emit(b.target,"click",{cancelable:!0,bubbles:!0,ctrlKey:b.ctrlKey,shiftKey:b.shiftKey,
metaKey:b.metaKey,altKey:b.altKey,_origType:b.type}))});var h=function(b,d){b.dojoClick=!0;return f(b,"click",d)};h.click=h;h.press=function(b,d){var a=f(b,r.press,function(a){("mousedown"!=a.type||k.isLeft(a))&&d(a)}),q=f(b,"keydown",function(a){(a.keyCode===e.ENTER||a.keyCode===e.SPACE)&&d(a)});return{remove:function(){a.remove();q.remove()}}};h.release=function(b,d){var a=f(b,r.release,function(a){("mouseup"!=a.type||k.isLeft(a))&&d(a)}),q=f(b,"keyup",function(a){(a.keyCode===e.ENTER||a.keyCode===
e.SPACE)&&d(a)});return{remove:function(){a.remove();q.remove()}}};h.move=r.move;return h})},"dijit/Destroyable":function(){define(["dojo/_base/array","dojo/aspect","dojo/_base/declare"],function(e,k,f){return f("dijit.Destroyable",null,{destroy:function(f){this._destroyed=!0},own:function(){var f=["destroyRecursive","destroy","remove"];e.forEach(arguments,function(m){function d(){b.remove();e.forEach(p,function(a){a.remove()})}var h,b=k.before(this,"destroy",function(a){m[h](a)}),p=[];m.then?(h=
"cancel",m.then(d,d)):e.forEach(f,function(a){"function"===typeof m[a]&&(h||(h=a),p.push(k.after(m,a,d,!0)))})},this);return arguments}})})},"dijit/_TemplatedMixin":function(){define("dojo/cache dojo/_base/declare dojo/dom-construct dojo/_base/lang dojo/on dojo/sniff dojo/string ./_AttachMixin".split(" "),function(e,k,f,r,m,d,h,b){var p=k("dijit._TemplatedMixin",b,{templateString:null,templatePath:null,_skipNodeCache:!1,searchContainerNode:!0,_stringRepl:function(a){var b=this.declaredClass,d=this;
return h.substitute(a,this,function(a,f){"!"==f.charAt(0)&&(a=r.getObject(f.substr(1),!1,d));if("undefined"==typeof a)throw Error(b+" template:"+f);return null==a?"":"!"==f.charAt(0)?a:this._escapeValue(""+a)},this)},_escapeValue:function(a){return a.replace(/["'<>&]/g,function(a){return{"\x26":"\x26amp;","\x3c":"\x26lt;","\x3e":"\x26gt;",'"':"\x26quot;","'":"\x26#x27;"}[a]})},buildRendering:function(){if(!this._rendered){this.templateString||(this.templateString=e(this.templatePath,{sanitize:!0}));
var a=p.getCachedTemplate(this.templateString,this._skipNodeCache,this.ownerDocument),b;if(r.isString(a)){if(b=f.toDom(this._stringRepl(a),this.ownerDocument),1!=b.nodeType)throw Error("Invalid template: "+a);}else b=a.cloneNode(!0);this.domNode=b}this.inherited(arguments);this._rendered||this._fillContent(this.srcNodeRef);this._rendered=!0},_fillContent:function(a){var b=this.containerNode;if(a&&b)for(;a.hasChildNodes();)b.appendChild(a.firstChild)}});p._templateCache={};p.getCachedTemplate=function(a,
b,d){var s=p._templateCache,e=a,n=s[e];if(n){try{if(!n.ownerDocument||n.ownerDocument==(d||document))return n}catch(l){}f.destroy(n)}a=h.trim(a);if(b||a.match(/\$\{([^\}]+)\}/g))return s[e]=a;b=f.toDom(a,d);if(1!=b.nodeType)throw Error("Invalid template: "+a);return s[e]=b};d("ie")&&m(window,"unload",function(){var a=p._templateCache,b;for(b in a){var d=a[b];"object"==typeof d&&f.destroy(d);delete a[b]}});return p})},"dojo/cache":function(){define(["./_base/kernel","./text"],function(e){return e.cache})},
"dijit/_AttachMixin":function(){define("require dojo/_base/array dojo/_base/connect dojo/_base/declare dojo/_base/lang dojo/mouse dojo/on dojo/touch ./_WidgetBase".split(" "),function(e,k,f,r,m,d,h,b,p){var a=m.delegate(b,{mouseenter:d.enter,mouseleave:d.leave,keypress:f._keypress}),q;f=r("dijit._AttachMixin",null,{constructor:function(){this._attachPoints=[];this._attachEvents=[]},buildRendering:function(){this.inherited(arguments);this._attachTemplateNodes(this.domNode);this._beforeFillContent()},
_beforeFillContent:function(){},_attachTemplateNodes:function(a){for(var b=a;;)if(1==b.nodeType&&(this._processTemplateNode(b,function(a,b){return a.getAttribute(b)},this._attach)||this.searchContainerNode)&&b.firstChild)b=b.firstChild;else{if(b==a)break;for(;!b.nextSibling;)if(b=b.parentNode,b==a)return;b=b.nextSibling}},_processTemplateNode:function(a,b,d){var f=!0,l=this.attachScope||this,t=b(a,"dojoAttachPoint")||b(a,"data-dojo-attach-point");if(t)for(var e=t.split(/\s*,\s*/);t=e.shift();)m.isArray(l[t])?
l[t].push(a):l[t]=a,f="containerNode"!=t,this._attachPoints.push(t);if(b=b(a,"dojoAttachEvent")||b(a,"data-dojo-attach-event")){t=b.split(/\s*,\s*/);for(e=m.trim;b=t.shift();)if(b){var h=null;-1!=b.indexOf(":")?(h=b.split(":"),b=e(h[0]),h=e(h[1])):b=e(b);h||(h=b);this._attachEvents.push(d(a,b,m.hitch(l,h)))}}return f},_attach:function(b,d,f){d=d.replace(/^on/,"").toLowerCase();d="dijitclick"==d?q||(q=e("./a11yclick")):a[d]||d;return h(b,d,f)},_detachTemplateNodes:function(){var a=this.attachScope||
this;k.forEach(this._attachPoints,function(b){delete a[b]});this._attachPoints=[];k.forEach(this._attachEvents,function(a){a.remove()});this._attachEvents=[]},destroyRendering:function(){this._detachTemplateNodes();this.inherited(arguments)}});m.extend(p,{dojoAttachEvent:"",dojoAttachPoint:""});return f})},"dijit/_WidgetBase":function(){define("require dojo/_base/array dojo/aspect dojo/_base/config dojo/_base/connect dojo/_base/declare dojo/dom dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/has dojo/_base/kernel dojo/_base/lang dojo/on dojo/ready dojo/Stateful dojo/topic dojo/_base/window ./Destroyable dojo/has!dojo-bidi?./_BidiMixin ./registry".split(" "),
function(e,k,f,r,m,d,h,b,p,a,q,A,s,y,n,l,t,F,u,z,B,G,w){function C(x){return function(a){b[a?"set":"remove"](this.domNode,x,a);this._set(x,a)}}s.add("dijit-legacy-requires",!y.isAsync);s.add("dojo-bidi",!1);s("dijit-legacy-requires")&&t(0,function(){e(["dijit/_base/manager"])});var D={};r=d("dijit._WidgetBase",[F,B],{id:"",_setIdAttr:"domNode",lang:"",_setLangAttr:C("lang"),dir:"",_setDirAttr:C("dir"),"class":"",_setClassAttr:{node:"domNode",type:"class"},_setTypeAttr:null,style:"",title:"",tooltip:"",
baseClass:"",srcNodeRef:null,domNode:null,containerNode:null,ownerDocument:null,_setOwnerDocumentAttr:function(a){this._set("ownerDocument",a)},attributeMap:{},_blankGif:r.blankGif||e.toUrl("dojo/resources/blank.gif"),_introspect:function(){var a=this.constructor;if(!a._setterAttrs){var b=a.prototype,c=a._setterAttrs=[],a=a._onMap={},g;for(g in b.attributeMap)c.push(g);for(g in b)/^on/.test(g)&&(a[g.substring(2).toLowerCase()]=g),/^_set[A-Z](.*)Attr$/.test(g)&&(g=g.charAt(4).toLowerCase()+g.substr(5,
g.length-9),(!b.attributeMap||!(g in b.attributeMap))&&c.push(g))}},postscript:function(a,b){this.create(a,b)},create:function(a,b){this._introspect();this.srcNodeRef=h.byId(b);this._connects=[];this._supportingWidgets=[];this.srcNodeRef&&"string"==typeof this.srcNodeRef.id&&(this.id=this.srcNodeRef.id);a&&(this.params=a,n.mixin(this,a));this.postMixInProperties();this.id||(this.id=w.getUniqueId(this.declaredClass.replace(/\./g,"_")),this.params&&delete this.params.id);this.ownerDocument=this.ownerDocument||
(this.srcNodeRef?this.srcNodeRef.ownerDocument:document);this.ownerDocumentBody=z.body(this.ownerDocument);w.add(this);this.buildRendering();var c;if(this.domNode){this._applyAttributes();var g=this.srcNodeRef;g&&(g.parentNode&&this.domNode!==g)&&(g.parentNode.replaceChild(this.domNode,g),c=!0);this.domNode.setAttribute("widgetId",this.id)}this.postCreate();c&&delete this.srcNodeRef;this._created=!0},_applyAttributes:function(){var a={},b;for(b in this.params||{})a[b]=this._get(b);k.forEach(this.constructor._setterAttrs,
function(b){if(!(b in a)){var g=this._get(b);g&&this.set(b,g)}},this);for(b in a)this.set(b,a[b])},postMixInProperties:function(){},buildRendering:function(){this.domNode||(this.domNode=this.srcNodeRef||this.ownerDocument.createElement("div"));if(this.baseClass){var a=this.baseClass.split(" ");this.isLeftToRight()||(a=a.concat(k.map(a,function(a){return a+"Rtl"})));p.add(this.domNode,a)}},postCreate:function(){},startup:function(){this._started||(this._started=!0,k.forEach(this.getChildren(),function(a){!a._started&&
(!a._destroyed&&n.isFunction(a.startup))&&(a.startup(),a._started=!0)}))},destroyRecursive:function(a){this._beingDestroyed=!0;this.destroyDescendants(a);this.destroy(a)},destroy:function(a){function b(c){c.destroyRecursive?c.destroyRecursive(a):c.destroy&&c.destroy(a)}this._beingDestroyed=!0;this.uninitialize();k.forEach(this._connects,n.hitch(this,"disconnect"));k.forEach(this._supportingWidgets,b);this.domNode&&k.forEach(w.findWidgets(this.domNode,this.containerNode),b);this.destroyRendering(a);
w.remove(this.id);this._destroyed=!0},destroyRendering:function(x){this.bgIframe&&(this.bgIframe.destroy(x),delete this.bgIframe);this.domNode&&(x?b.remove(this.domNode,"widgetId"):a.destroy(this.domNode),delete this.domNode);this.srcNodeRef&&(x||a.destroy(this.srcNodeRef),delete this.srcNodeRef)},destroyDescendants:function(a){k.forEach(this.getChildren(),function(b){b.destroyRecursive&&b.destroyRecursive(a)})},uninitialize:function(){return!1},_setStyleAttr:function(a){var b=this.domNode;n.isObject(a)?
A.set(b,a):b.style.cssText=b.style.cssText?b.style.cssText+("; "+a):a;this._set("style",a)},_attrToDom:function(a,v,c){c=3<=arguments.length?c:this.attributeMap[a];k.forEach(n.isArray(c)?c:[c],function(g){var c=this[g.node||g||"domNode"];switch(g.type||"attribute"){case "attribute":n.isFunction(v)&&(v=n.hitch(this,v));g=g.attribute?g.attribute:/^on[A-Z][a-zA-Z]*$/.test(a)?a.toLowerCase():a;c.tagName?b.set(c,g,v):c.set(g,v);break;case "innerText":c.innerHTML="";c.appendChild(this.ownerDocument.createTextNode(v));
break;case "innerHTML":c.innerHTML=v;break;case "class":p.replace(c,v,this[a])}},this)},get:function(a){var b=this._getAttrNames(a);return this[b.g]?this[b.g]():this._get(a)},set:function(a,b){if("object"===typeof a){for(var c in a)this.set(c,a[c]);return this}c=this._getAttrNames(a);var g=this[c.s];if(n.isFunction(g))var d=g.apply(this,Array.prototype.slice.call(arguments,1));else{var g=this.focusNode&&!n.isFunction(this.focusNode)?"focusNode":"domNode",f=this[g]&&this[g].tagName,e;if(e=f)if(!(e=
D[f])){e=this[g];var h={},E;for(E in e)h[E.toLowerCase()]=!0;e=D[f]=h}E=e;c=a in this.attributeMap?this.attributeMap[a]:c.s in this?this[c.s]:E&&c.l in E&&"function"!=typeof b||/^aria-|^data-|^role$/.test(a)?g:null;null!=c&&this._attrToDom(a,b,c);this._set(a,b)}return d||this},_attrPairNames:{},_getAttrNames:function(a){var b=this._attrPairNames;if(b[a])return b[a];var c=a.replace(/^[a-z]|-[a-zA-Z]/g,function(a){return a.charAt(a.length-1).toUpperCase()});return b[a]={n:a+"Node",s:"_set"+c+"Attr",
g:"_get"+c+"Attr",l:c.toLowerCase()}},_set:function(a,b){var c=this[a];this[a]=b;if(this._created&&!(c===b||c!==c&&b!==b))this._watchCallbacks&&this._watchCallbacks(a,c,b),this.emit("attrmodified-"+a,{detail:{prevValue:c,newValue:b}})},_get:function(a){return this[a]},emit:function(a,b,c){b=b||{};void 0===b.bubbles&&(b.bubbles=!0);void 0===b.cancelable&&(b.cancelable=!0);b.detail||(b.detail={});b.detail.widget=this;var g,d=this["on"+a];d&&(g=d.apply(this,c?c:[b]));this._started&&!this._beingDestroyed&&
l.emit(this.domNode,a.toLowerCase(),b);return g},on:function(a,b){var c=this._onMap(a);return c?f.after(this,c,b,!0):this.own(l(this.domNode,a,b))[0]},_onMap:function(a){var b=this.constructor,c=b._onMap;if(!c){var c=b._onMap={},g;for(g in b.prototype)/^on/.test(g)&&(c[g.replace(/^on/,"").toLowerCase()]=g)}return c["string"==typeof a&&a.toLowerCase()]},toString:function(){return"[Widget "+this.declaredClass+", "+(this.id||"NO ID")+"]"},getChildren:function(){return this.containerNode?w.findWidgets(this.containerNode):
[]},getParent:function(){return w.getEnclosingWidget(this.domNode.parentNode)},connect:function(a,b,c){return this.own(m.connect(a,b,this,c))[0]},disconnect:function(a){a.remove()},subscribe:function(a,b){return this.own(u.subscribe(a,n.hitch(this,b)))[0]},unsubscribe:function(a){a.remove()},isLeftToRight:function(){return this.dir?"ltr"==this.dir.toLowerCase():q.isBodyLtr(this.ownerDocument)},isFocusable:function(){return this.focus&&"none"!=A.get(this.domNode,"display")},placeAt:function(b,d){var c=
!b.tagName&&w.byId(b);c&&c.addChild&&(!d||"number"===typeof d)?c.addChild(this,d):(c=c&&"domNode"in c?c.containerNode&&!/after|before|replace/.test(d||"")?c.containerNode:c.domNode:h.byId(b,this.ownerDocument),a.place(this.domNode,c,d),!this._started&&(this.getParent()||{})._started&&this.startup());return this},defer:function(a,b){var c=setTimeout(n.hitch(this,function(){c&&(c=null,this._destroyed||n.hitch(this,a)())}),b||0);return{remove:function(){c&&(clearTimeout(c),c=null);return null}}}});s("dojo-bidi")&&
r.extend(G);return r})},"dojo/touch":function(){define("./_base/kernel ./aspect ./dom ./dom-class ./_base/lang ./on ./has ./mouse ./domReady ./_base/window".split(" "),function(e,k,f,r,m,d,h,b,p,a){function q(a,b,c){return n&&c?function(a,b){return d(a,c,b)}:t?function(c,f){var e=d(c,b,function(a){f.call(this,a);v=(new Date).getTime()}),h=d(c,a,function(a){(!v||(new Date).getTime()>v+1E3)&&f.call(this,a)});return{remove:function(){e.remove();h.remove()}}}:function(b,c){return d(b,a,c)}}function A(a){do if(void 0!==
a.dojoClick)return a;while(a=a.parentNode)}function s(b,c,e){var h=A(b.target);if(u=!b.target.disabled&&h&&h.dojoClick)if(B=(z="useTarget"==u)?h:b.target,z&&b.preventDefault(),G=b.changedTouches?b.changedTouches[0].pageX-a.global.pageXOffset:b.clientX,w=b.changedTouches?b.changedTouches[0].pageY-a.global.pageYOffset:b.clientY,C=("object"==typeof u?u.x:"number"==typeof u?u:0)||4,D=("object"==typeof u?u.y:"number"==typeof u?u:0)||4,!F){F=!0;var l=function(b){u=z?f.isDescendant(a.doc.elementFromPoint(b.changedTouches?
b.changedTouches[0].pageX-a.global.pageXOffset:b.clientX,b.changedTouches?b.changedTouches[0].pageY-a.global.pageYOffset:b.clientY),B):u&&(b.changedTouches?b.changedTouches[0].target:b.target)==B&&Math.abs((b.changedTouches?b.changedTouches[0].pageX-a.global.pageXOffset:b.clientX)-G)<=C&&Math.abs((b.changedTouches?b.changedTouches[0].pageY-a.global.pageYOffset:b.clientY)-w)<=D};a.doc.addEventListener(c,function(a){l(a);z&&a.preventDefault()},!0);a.doc.addEventListener(e,function(a){l(a);if(u){x=(new Date).getTime();
var b=z?B:a.target;"LABEL"===b.tagName&&(b=f.byId(b.getAttribute("for"))||b);var c=a.changedTouches?a.changedTouches[0]:a,g=document.createEvent("MouseEvents");g._dojo_click=!0;g.initMouseEvent("click",!0,!0,a.view,a.detail,c.screenX,c.screenY,c.clientX,c.clientY,a.ctrlKey,a.altKey,a.shiftKey,a.metaKey,0,null);setTimeout(function(){d.emit(b,"click",g);x=(new Date).getTime()},0)}},!0);b=function(b){a.doc.addEventListener(b,function(a){!a._dojo_click&&((new Date).getTime()<=x+1E3&&!("INPUT"==a.target.tagName&&
r.contains(a.target,"dijitOffScreen")))&&(a.stopPropagation(),a.stopImmediatePropagation&&a.stopImmediatePropagation(),"click"==b&&(("INPUT"!=a.target.tagName||"radio"==a.target.type||"checkbox"==a.target.type)&&"TEXTAREA"!=a.target.tagName&&"AUDIO"!=a.target.tagName&&"VIDEO"!=a.target.tagName)&&a.preventDefault())},!0)};b("click");b("mousedown");b("mouseup")}}var y=5>h("ios"),n=h("pointer-events")||h("MSPointer"),l=function(){var a={},b;for(b in{down:1,move:1,up:1,cancel:1,over:1,out:1})a[b]=h("MSPointer")?
"MSPointer"+b.charAt(0).toUpperCase()+b.slice(1):"pointer"+b;return a}(),t=h("touch-events"),F,u,z=!1,B,G,w,C,D,x,v,c;n?p(function(){a.doc.addEventListener(l.down,function(a){s(a,l.move,l.up)},!0)}):t&&p(function(){function b(a){var c=m.delegate(a,{bubbles:!0});6<=h("ios")&&(c.touches=a.touches,c.altKey=a.altKey,c.changedTouches=a.changedTouches,c.ctrlKey=a.ctrlKey,c.metaKey=a.metaKey,c.shiftKey=a.shiftKey,c.targetTouches=a.targetTouches);return c}c=a.body();a.doc.addEventListener("touchstart",function(a){v=
(new Date).getTime();var b=c;c=a.target;d.emit(b,"dojotouchout",{relatedTarget:c,bubbles:!0});d.emit(c,"dojotouchover",{relatedTarget:b,bubbles:!0});s(a,"touchmove","touchend")},!0);d(a.doc,"touchmove",function(f){v=(new Date).getTime();var e=a.doc.elementFromPoint(f.pageX-(y?0:a.global.pageXOffset),f.pageY-(y?0:a.global.pageYOffset));e&&(c!==e&&(d.emit(c,"dojotouchout",{relatedTarget:e,bubbles:!0}),d.emit(e,"dojotouchover",{relatedTarget:c,bubbles:!0}),c=e),d.emit(e,"dojotouchmove",b(f))||f.preventDefault())});
d(a.doc,"touchend",function(c){v=(new Date).getTime();var f=a.doc.elementFromPoint(c.pageX-(y?0:a.global.pageXOffset),c.pageY-(y?0:a.global.pageYOffset))||a.body();d.emit(f,"dojotouchend",b(c))})});k={press:q("mousedown","touchstart",l.down),move:q("mousemove","dojotouchmove",l.move),release:q("mouseup","dojotouchend",l.up),cancel:q(b.leave,"touchcancel",n?l.cancel:null),over:q("mouseover","dojotouchover",l.over),out:q("mouseout","dojotouchout",l.out),enter:b._eventHandler(q("mouseover","dojotouchover",
l.over)),leave:b._eventHandler(q("mouseout","dojotouchout",l.out))};return e.touch=k})},"url:esri/dijit/templates/HomeButton.html":'\x3cdiv class\x3d"${theme}" role\x3d"presentation"\x3e\r\n    \x3cdiv class\x3d"${_css.container}"\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"_homeNode" title\x3d"${_i18n.widgets.homeButton.home.title}" role\x3d"button" class\x3d"${_css.home}"\x3e\x3cspan\x3e${_i18n.widgets.homeButton.home.button}\x3c/span\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e',
"*noref":1}});
define("esri/dijit/HomeButton","dojo/Evented dojo/_base/declare dojo/_base/lang dojo/has ../kernel dijit/_WidgetBase dijit/a11yclick dijit/_TemplatedMixin dojo/on dojo/Deferred dojo/text!./templates/HomeButton.html dojo/i18n!../nls/jsapi dojo/dom-class dojo/dom-style".split(" "),function(e,k,f,r,m,d,h,b,p,a,q,A,s,y){e=k("esri.dijit.HomeButton",[d,b,e],{templateString:q,options:{theme:"HomeButton",map:null,extent:null,fit:!1,visible:!0},constructor:function(a,b){var d=f.mixin({},this.options,a);this.domNode=
b;this._i18n=A;this.set("map",d.map);this.set("theme",d.theme);this.set("visible",d.visible);this.set("extent",d.extent);this.set("fit",d.fit);this.watch("theme",this._updateThemeWatch);this.watch("visible",this._visible);this._css={container:"homeContainer",home:"home",loading:"loading"}},postCreate:function(){this.inherited(arguments);this.own(p(this._homeNode,h,f.hitch(this,this.home)))},startup:function(){this.inherited(arguments);this.map||(this.destroy(),console.log("HomeButton::map required"));
if(this.map.loaded)this._init();else p.once(this.map,"load",f.hitch(this,function(){this._init()}))},destroy:function(){this.inherited(arguments)},home:function(){var b=new a,d=this.get("extent");this._showLoading();var e={extent:d};d?this.map.extent!==d?this.map.setExtent(d,this.get("fit")).then(f.hitch(this,function(){this._hideLoading();this.emit("home",e);b.resolve(e)}),f.hitch(this,function(a){a||(a=Error("HomeButton::Error setting map extent"));e.error=a;this.emit("home",e);b.reject(a)})):(this._hideLoading(),
this.emit("home",e),b.resolve(e)):(this._hideLoading(),d=Error("HomeButton::home extent is undefined"),e.error=d,this.emit("home",e),b.reject(d));return b.promise},show:function(){this.set("visible",!0)},hide:function(){this.set("visible",!1)},_init:function(){this._visible();this.get("extent")||this.set("extent",this.map.extent);this.set("loaded",!0);this.emit("load",{})},_showLoading:function(){s.add(this._homeNode,this._css.loading)},_hideLoading:function(){s.remove(this._homeNode,this._css.loading)},
_updateThemeWatch:function(a,b,d){s.remove(this.domNode,b);s.add(this.domNode,d)},_visible:function(){this.get("visible")?y.set(this.domNode,"display","block"):y.set(this.domNode,"display","none")}});r("extend-esri")&&f.setObject("dijit.HomeButton",e,m);return e});